### ISSUE TITLE
Magic

### ISSUE THREAD

**Issue by OverLordGoldDragon** [sphinx-gallery/sphinx-gallery#1026]
Is Jupyter magic supported? Default Jupyter plotting degrades plot quality, but a certain command undoes that - see below.

This doesn't work, with `ipython == None` as `sphinx-gallery` runs plain Python then builds HTML from it:

```python
from IPython import get_ipython
ipython = get_ipython()
ipython.run_line_magic("config", "InlineBackend.figure_format = 'retina'")
```

`nbsphinx` with `sphx_glr_python_to_jupyter` and `jupyter nbconvert` is an option but would take some work to overwrite `sphinx-gallery` outputs.

<hr>

<img src="https://user-images.githubusercontent.com/16495490/193453069-5fa34fad-32c2-4c5b-9727-1d01ffee36b8.png" width="600">

<details><summary><b>full code</b></summary>

```python
import numpy as np
import matplotlib.pyplot as plt

def plot():
    fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=72)
    ax.imshow(np.random.uniform(0, 1, (128, 128)),
              cmap='bwr', aspect='auto', interpolation='none')
    ax.set_title("My image", weight='bold', fontsize=20)
    plt.show()

#%%
plot()
#%%
%config InlineBackend.figure_format = 'retina'
plot()
```

</details>

**Comment by larsoner** [comment]
Jupyter magic is only supported in the sense that it's embedded in the `.ipynb` that are generated. SG runs things using Python not `ipython` so during gallery generation itself these will have no effect. Instead you can put necessary tweaks for plotting with Agg in a custom `resetter` if you want (e.g., `figure.dpi`)

**Comment by OverLordGoldDragon** [comment]
@larsoner The low quality is a dealbreaker for me. As workaroud, I figure to feed SG's `py -> ipynb` to `nbsphinx`, though it may be just for this one thing. Note, it's not the image _files_, but how they're _displayed_: after the magic, we get `<img class="no-scaled-link"`, and I can't find that class's source with Firefox's dev tools. Any ideas? The degradation is also rather obvious, it'd benefit SG to fix this.

**Comment by larsoner** [comment]
So you're talking about how it looks when actually just running the `ipynb` made by SG? I thought you were talking about some HTML that SG generated.

Have you seen https://sphinx-gallery.github.io/stable/configuration.html#add-your-own-first-and-last-notebook-cell ? Maybe it does what you need already?

**Comment by OverLordGoldDragon** [comment]
I do refer to the HTML. `nbsphinx` generates HTML by running `ipynb`, unlike SG.

**Comment by larsoner** [comment]
> I do refer to the HTML. nbsphinx generates HTML by running ipynb, unlike SG.

Sounds like you are referring to *HTML generated by nbsphinx*, and I am referring to *HTML generated by SG*. In this repo I'm only worried about SG outputs. So let's not worry about the HTML that `nbsphinx` generates and think instead about a SG output -- the relevant one here would be the `.ipynb`, right? If so, have you seen/tried the link above where you can config the magic in the first notebook cell to suit your needs?

**Comment by OverLordGoldDragon** [comment]
I refer to SG, was just pointing the difference. I did try it, and it does affect the `ipynb`, but not HTML, as it's supposed to?

**Comment by larsoner** [comment]
Just to make sure I understand what you're doing -- you run SG, get an ipynb, ignore any other SG outputs, then run the obtained `.ipynb` in Jupyter notebook and `nbsphinx`, and both show the same problem? Or if `jupyter notebook` shows no issue but `nbsphinx` does on the `.ipynb`... it seems like a `nbsphinx` bug, no?

Just to clarify the terminology -- to me this doesn't have to do with "HTML that SG produces", as the "HTML that SG produces" is canonically the `auto_examples/whatever.html` you get by the initial SG run + pure Python code execution during some doc build.

Hence to me -- based on what I can gather -- the problem sounds like it's potentially with the "ipynb that SG produces" when you follow it with some downstream tool that renders the *SG .ipynb output* to HTML, if that makes sense. I think the distinction is important because we need to make sure we're talking about the same stuff.

So when you say:

> I did try it, and it does affect the ipynb, but not HTML, as it's supposed to?

I want to be clear about what you mean by "but not the HTML". So far I thought we were talking about the `.ipynb` followed by some other tool, but now I wonder if you're actually talking about some `auto_examples/whatever.html` that SG produced by running pure python code.

**Comment by OverLordGoldDragon** [comment]
I refer to following the completely standard SG protocol, with no `nbsphinx` or anything else. My `nbsphinx` comments are about my workaround to this problem, problem being:

  - **HTML generated by SG** _displays_ low quality images from normal quality images it produces, and `first_notebook_cell` doesn't fix that because SG produces HTML from `py`, not `ipynb`.

Next, `nbsphinx` fixes that because it runs the `ipynb`. I create the `ipynb` using SG. So

 - **HTML generated by `nbsphinx`** from `ipynb` generated by SG, displays normal quality images.

The "low quality images" isn't an SG problem, it's a Jupyter problem. One fix I imagine is, adding the contents of `class="no-scaled-link"` to SG's images class, or that class itself to every `<img>` inside of `<body>`, but we'd first have to find that class itself, which I could look into, but wonder if there's another way.

**Comment by larsoner** [comment]
> HTML generated by SG displays low quality images from normal quality images it produces

Okay so it is in `auto_examples/whatever.html` where you see this. Can you reproduce the problem with `sphinx_gallery/tests/tinybuild` so I can see it in its output `.html` files directly? That makes it easy to see the problem locally instead of talking in the abstract.

> The "low quality images" isn't an SG problem, it's a Jupyter problem. 

... and now I'm confused again. SG "standard build" HTML does nothing with Jupyter (and how it might render HTML), so how is this a SG HTML <-> Jupyter problem?

> One fix I imagine is, adding the contents of class="no-scaled-link" to SG's images class, or that class itself to every <img> inside of <body>

Probably a CSS fix should work since all SG-produced images in HTML get standard class names like `sphx-glr-single-img` or the multi equivalent:

![Screenshot from 2022-10-03 17-11-08](https://user-images.githubusercontent.com/2365790/193683375-9df3514e-b821-4025-a761-dbc0cfb7c91b.png)

**Comment by OverLordGoldDragon** [comment]
Correction, it's probably not `no-scaled-link`, that's an `nbsphinx` class yet this is reproduced in standard Jupyter without that class. It's also not "low quality display of normal quality images", the images themselves differ in Jupyter, yet I saw different behavior in SG... will update.

**Comment by OverLordGoldDragon** [comment]
> how is this a SG HTML <-> Jupyter problem?

In fact it may be a browser problem - Windows image viewer shows HD, Firefoxs shows LD at 100% zoom but HD at 80% zoom - either way that magic command fixes things.

**Comment by OverLordGoldDragon** [comment]
So `tinybuild` actually produces normal plots, but I based my project off of [sample-project](https://github.com/sphinx-gallery/sample-project). Steps to reproduce:

  1. Clone
  2. Fix [bug(?)](https://github.com/sphinx-gallery/sample-project/pull/10)
  3. Add `sample-gallery-1/plot_4.py`:

```python
# -*- coding: utf-8 -*-
"""
Plot 4
======
Yes
"""

import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 1, figsize=(5, 5), dpi=72)
ax.imshow(np.random.uniform(0, 1, (128, 128)),
          cmap='bwr', aspect='auto', interpolation='none')
ax.set_title("My image", weight='bold', fontsize=20)
plt.show()
```

 4. `cd` into `docs/` and `make html`, then open `plot_4.html`

**Comment by OverLordGoldDragon** [comment]
I traced this to `image_srcset`, which makes sense considering my former comments. `x1.5` beats `x2` for me so higher != better, which is another problem. I wonder how this compares against the magic command, but that's off-topic. Perhaps docs should mention this option as worth testing to see if image quality improves significantly.

Thanks for feedback.
