### ISSUE TITLE
BUG Sphinx `docname` from source-read event is sometimes `None`

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#1175]
Doc build and several `test_full.py` tests on Windows CI workflow failing on recent PRs (e.g., #1173, #1172)

Windows `test_full.py` failures are all due to:
```
sphinx_gallery\gen_gallery.py:919: in write_api_entry_usage
    "sg_api_usage" not in docname
E   TypeError: argument of type 'NoneType' is not iterable
```
Similarly doc build error is:
```
An error happened in rendering the page advanced.
Reason: AttributeError("'TocTree' object has no attribute 'get_toctree_ancestors'")
```
AFAICT `docname` should: "Returns the docname of the document currently being parsed."
https://www.sphinx-doc.org/en/master/extdev/envapi.html#sphinx.environment.BuildEnvironment.docname

'source-read' event emits `env.docname` which  does not seem to have changed recently: https://github.com/sphinx-doc/sphinx/blob/da9f8a5c33ad5eeef05dd780f2988f3ff7351ef3/sphinx/environment/__init__.py#L545

Seems to be a Sphinx issue as there was a release some hours ago.

**Comment by AA-Turner** [comment]
Dear @lucyleeow, @larsoner,

I believe I've found the source of this bug.

https://github.com/sphinx-doc/sphinx/pull/11510 fixed a previous failure to emit ``source-read`` for uses of the ``.. include::`` directive. Such directives are emitted by the ``.. minigallery::`` directive. ``BuildEnvironment.path2doc`` will then try and resolve a path similar to ``gen_modules/backreferences/sphinx_gallery.backreferences.identify_names.examples`` to a document name, which will fail as the document does not have a suffix contained within ``app.config.source_suffix``. 

The solution is to write the ``.examples`` files to disk with a ``.rst`` suffix, and ensure that ``.examples.rst`` or ``.rst`` is contained in ``config.source_suffix``: the docname will be the relative path from the source directory with the suffix removed.

A

**Comment by AA-Turner** [comment]
Adding a breakpoint at ``sphinx.directives.other::Include.run._insert_input()`` should be helpful in reproducing this on your end.

A

**Comment by larsoner** [comment]
@AA-Turner thanks for the in-depth investigation here!

Usually I see files destined to be `.. include::`ed in the source tree with suffixes like `.inc` to mark as "don't render as RST alone, it will be included". The `.examples` is more or less this pattern -- don't render by default but allow to be included.

So I think for us the right thing to do here, rather than changing to `.rst` -- which will cause these little snippets to be rendered on their own in addition to being inserted I think -- would be to properly handle the `None` case, which is what the workaround (which I was worried was a hack) is doing. So I think we're okay here!
