### ISSUE TITLE
Add instructions about how to build the documentation locally

### ISSUE THREAD

**Issue by lesteve** [sphinx-gallery/sphinx-gallery#12]
I feel there is a section missing in http://sphinx-gallery.readthedocs.org/en/latest/getting_started.html in order to explain how to build the documentation locally and where to find the generated html, in particular the location of the gallery. That would probably go before "Setting up your project".

**Comment by Titan-C** [comment]
Indeed it is not clear enough. But the last paragraph does say the gallery is located in the auto_examples directory. And for the build process it is just part of the general documentation controlled by sphinx. I shall add a line saying `make html` in the documentation directory.
Other thing that might be missing is to extend the Makefile instruction clean, so that it also deletes the auto_examples directory and other generated ones. And also to include these directories in the .gitignore file.

**Comment by lesteve** [comment]
Just for the sake of clarity: I would just add a "How to build the documentation locally" section with instructions like `cd doc && make html` + `your_favourite_browser `_build/html/auto_examples/index.html`.

> Other thing that might be missing is to extend the Makefile instruction clean, so that it also deletes the auto_examples directory and other generated ones.

Good idea I believe the scikit-learn and nilearn doc/Makefile do that already.

Yep

**Comment by Titan-C** [comment]
done in release 0.0.5
