### ISSUE TITLE
Navigation bar TOC rendering for nested galleries

### ISSUE THREAD

**Issue by remy-abergel** [sphinx-gallery/sphinx-gallery#1323]
Hi, 

I am trying to document using sphinx a Python package with nested example galleries. I made a simple package to reproduce the issue I am facing. This package can be downloaded here: [pypkg.zip](https://github.com/user-attachments/files/15752783/pypkg.zip), it has the following structure:
```
.
├── docs/
│   ├── conf.py
│   ├── index.md
│   ├── installation.md
│   ├── make.bat
│   └── Makefile
├── examples/
│   ├── experiments/
│       ├── plot_exp_demo1.py
│       ├── plot_exp_demo2.py
│       └── README.txt
│   └── tutorials/
│       ├── 3d/
│           ├── plot_tuto_3d_demo1.py
│           ├── plot_tuto_3d_demo2.py
│           └── README.txt
│       ├── plot_tuto_2d_demo1.py
│       ├── plot_tuto_2d_demo2.py
│       └── README.txt
├── pyproject.toml
├── README.md
└── src/
    └── pypkg/
        ├── foo.py
        └── __init__.py

``` 

The sphinx build works fine and the rendering of the nested gallery seems nice at a first glance: 

![screenshot1](https://github.com/sphinx-gallery/sphinx-gallery/assets/60599693/b1f2414d-9df9-4f3d-8933-4c23c9825f8c)

However, I end up with a strange rendering of the `tutorials/3D` gallery in the navigation bar: 

![screenshot2](https://github.com/sphinx-gallery/sphinx-gallery/assets/60599693/870717f6-f6b1-4261-8b30-d16a21380861)

I am probably using sphinx-gallery in a wrong way, could you please let me know how I can get rid of the undesired `3D/3D` heading in the navigation bar? 

Many thanks!

**Comment by lucyleeow** [comment]
So AFAICT this is intentional, see: https://github.com/sphinx-gallery/sphinx-gallery/pull/944#discussion_r916603188 and https://github.com/sphinx-gallery/sphinx-gallery/issues/1262#issuecomment-1958751206

In https://github.com/sphinx-gallery/sphinx-gallery/issues/1323#issuecomment-2156641586, when you set `'nested_sections': True` you get one toctree at the end of the `index.rst` file, which gives the spurious headings:

```
.. toctree::
   :hidden:
   :includehidden:


   /_gallery/tutorials/2d/index.rst
   /_gallery/tutorials/3d/index.rst
```

when you set `'nested_sections': False` you get a toctree per section/sub-gallery, with each listing all example files in that section.

```
.. toctree::
   :hidden:

   /_gallery/tutorials/2d/plot_tuto_2d_demo1
   /_gallery/tutorials/2d/plot_tuto_2d_demo2
```
and
```
.. toctree::
   :hidden:

   /_gallery/tutorials/3d/plot_tuto_3d_demo2
   /_gallery/tutorials/3d/plot_tuto_3d_demo1

```
This seems to play well with your theme but it seems that the appearance of the sidebar and these toctrees configs varies with theme. Indeed with Sphinx-Gallery itself, we had to change nested_sections setting when we changed theme.

Since you managed to make it work I don't think we need to do more here but I do think our docs can be improved. I have no idea what 'fuzzy' toctree means.

cc @alexisthual

**Comment by lucyleeow** [comment]
> Regarding v0.0.2 of my pypkg (attached in my https://github.com/sphinx-gallery/sphinx-gallery/issues/1323#issuecomment-2156641586)

Does setting `nested_sections: False` work here?

I don't think you did anything wrong. I am not actually sure what problem the note is meant to solve. I don't think moving examples from the root gallery to their own sub folder is meant to work for every theme.

**Comment by lucyleeow** [comment]
I think it's just meant to deal with side bar appearance for galleries with sub sections. Have a read of the original issue #855 for more.
Also I agree the doc is confusing. I've updated it in #1326, let me know if that makes more sense/any areas to improve on.

**Comment by lucyleeow** [comment]
> This is not exactly what I observe when I set 'nested_sections': False in pypkg (v0.0.2): I get one index.rst file per subfolder, i.e., one index.rst file into the _gallery/tutorials subfolder and one index.rst file into the _gallery/experiments subfolder. 

Gallery folder (what you have in your `examples_dirs` config) = `../examples/experiments` and `../examples/tutorials`)
Sub folders are folders inside gallery folders, e.g., for `../examples/tutorials` the sub folders are `2d/` and `3d/`.

In the docs (and in our code) we use the term subsection to mean a sub-folder inside a gallery folder, aka a 'sub-gallery'.

I think with the above definitions as to what a 'sub section'/'sub folder' is, the `nested_sections` config descriptions should hopefully now make sense.

I can try and improve the docs to make this clearer.
