### ISSUE TITLE
"edit on github" links on example pages are broken

### ISSUE THREAD

**Issue by anntzer** [sphinx-gallery/sphinx-gallery#154]
e.g. at the top right of https://sphinx-gallery.readthedocs.io/en/latest/auto_examples/plot_gallery_version.html

**Comment by lesteve** [comment]
Because rst files are automatically generated, they are not in the repo.

One option is to remove the "Edit on github" link. There is a SO [answer](http://stackoverflow.com/a/36723647) about that.

If we could have the "Edit on github link" point to the python example that would be great, but I am not sure how feasible this is.

**Comment by anntzer** [comment]
I think the first option is not optimal but better than the current situation.

**Comment by Titan-C** [comment]
I have prepared PR #156 it removes the edit on github and leaves in place the view page source link
