### ISSUE TITLE
Support of other languages

### ISSUE THREAD

**Issue by chsasank** [sphinx-gallery/sphinx-gallery#194]
Hi,

Can we support other programming languages for the gallery? 
We should be able to extract rst and code from other languages, like in python. Of course we cannot implement plot_examples, but we should be able to deal with examples which are just to be presented.

This is relevant because some projects have multi language apis.

An extension to the above is to render multi-language examples into one single gallery page. For example, `example.js`, `example.py`, `example.cpp` will all render in to one page with a js based switch/button to select the language to be displayed.

Please let me know if you think this will be useful, I will contribute. 
It'll be great if somebody can guide me on how to get started with the contribution.

**Comment by Titan-C** [comment]
> Can we support other programming languages for the gallery?
> We should be able to extract rst and code from other languages, like
> in python.

I do see supporting other languages as convenient, although it is not in
our current priority line. The project itself is not far either from
making that possible(I guess). I'm working on PR #160, to make
sphinx-gallery more modular and functional. The idea is having the
components separated so that extending the behavior will be easier. In
this case parsing source files of other languages, shall be the only
thing to review.

> Of course we cannot implement plot_examples, but we should be able to
> deal with examples which are just to be presented.

Indeed parsing a source file into HTML is the simplest first
step. Execution of other languages, is out of my knowledge for now, but we
can always explore how they do it in the Jupyter project.

> An extension to the above is to render multi-language examples into one single gallery page. For example, `example.js`, `example.py`, `example.cpp` will all render in to one page with a js based switch/button to select the language to be displayed.
>

I don't understand what you want with this example. Can you elaborate on
this? Only one extra comment, in this project we avoid the use of
javascript, if it can be done with HTML+CSS that's the way we go.

> Please let me know if you think this will be useful, I will contribute.
> It'll be great if somebody can guide me on how to get started with the contribution.

Yes, it is useful. Our goal with sphinx-gallery is to make writing
documentation easy. Commented code is great documentation, to teach
people how to use a package. Supporting other languages is within our
scope, just not a current priority. Your help is very welcomed.

Contributing shall be simple(I should write the contributing.md file
#91). Start small, look around the code base, our issue list, our pull
requests, look for things that could be improved simply and send us a
Pull request. We will give you feedback and once we like your changes
we'll adopt them.

To go directly into you goal of supporting other languages, I'm not sure
on which path to take. Should it be developed as an extension of the
gallery? a plugin? directly embedded in how the program parses the
examples? Keep us telling your ideas, get a prototype working. There
will be more issues than just writing a parser to transform from a code
source file to a rst file. Sphinx-Gallery parses the code files many
times for various goals, not only to make the website, but to discover
which functions where used to create the backreferences, or to create
the links to the online documentations of the functions used. You'll
have to implement flow controls that let you skip those steps if the
code is not Python. Might not be as easy as how I thought when I started
writing.

**Comment by chsasank** [comment]
First off, thanks for the concise reply.

> I don't understand what you want with this example. Can you elaborate on
this? 
I'm working on [SimpleITK](http://www.simpleitk.org). It is a simplified layer over ITK with wrappers for languages like python, lua, java etc. The [examples](https://github.com/SimpleITK/SimpleITK/tree/master/Examples) has repeated examples for many languages. They all look almost the same. For example:

read.py might look like
```python
""""
How to read nii.gz Images
===================
""""
import SimpleITK as sitk
img = sitk.ReadImage('file.nii.gz')
sitk.WriteImage(img, 'file2.nii.gz')
```

read.lua might look like:
```lua
--[[
How to read nii.gz images
===================
--]]
sitk = require 'SimpleITK'
img = sitk.ReadImage('file.nii.gz')
sitk.WriteImage(img, 'file2.nii.gz')
```

Now, it doesn't make sense to have two different gallery pages because these two look very similar. Also involved with this is maintaining the prose for each of read.py and read.lua separately. 

It'll be great if these two are in the same page with an option to select the language you want to see the code in.

> You'll have to implement flow controls that let you skip those steps if the
code is not Python.

It looks like it's not as easy as I assumed it would be. At any rate, I will try to get a first cut implementation working and take feedback from you.

**Comment by lesteve** [comment]
I thought I commented on this issue a while ago but apparently not, sorry about that.

sphinx-gallery is a small project and we have limited resources to devote to it, so we need to chose carefully the features we implement in order to keep it maintainable on the long term.

In this instance, my opinion is that this feature is something that 99% of packages using sphinx-gallery do not need. Implementing this feature does seem highly non-trivial. All in all the benefit is not worth the cost.

For SimpleITK purposes I am not sure what the best course of action is. Maybe there is a way to hack into the rst or html produced by sphinx-gallery. We would try our best to help you if you chose this route but I don't think this is is very likely to be included in sphinx-gallery.

**Comment by chsasank** [comment]
I agree that this feature might not be required for most of the existing libraries. 

> Implementing this feature does seem highly non-trivial. 

I've made an attempt at #197. I did have to do quite a lot of refactoring. 

> I don't think this is is very likely to be included in sphinx-gallery.

I think that's fine. May be you can keep it as a branch if you want to work on it later. I can use my fork for SimpleITK purposes.
