### ISSUE TITLE
Notebook styled examples without execution

### ISSUE THREAD

**Issue by chsasank** [sphinx-gallery/sphinx-gallery#204]
Hi,

Is it possible to have notebook styled examples without actually executing them?

If not, would you be interested in a PR? I think it can be done without too much modification to code base.

Sasank.

**Comment by lesteve** [comment]
You can convert example python files to jupyter notebooks as mentioned in: http://sphinx-gallery.readthedocs.io/en/latest/utils.html?highlight=jupyter#convert-python-scripts-into-jupyter-notebooks.

If that answers your question, can you close the issue?

**Comment by chsasank** [comment]
Let me elaborate my question.

Suppose we have `plot_example.py` and `example.py`. Of these `example.py` will not be executed while `plot_example.py` will be.
I know that if `plot_example.py` has  commented block, the output looks like notebook; code explained by comments above. 

Now, I want to know if there's a way to write `example.py` so that the output looks like notebook. I don't want it to be executed.

**Comment by lesteve** [comment]
If I understand you correctly you are saying that when an example is not executed, the output HTML doesn't have a notebook-like look (e.g. multiple cells). You are not talking about jupyter notebooks.

It feels like an oversight and a PR would be more than welcome. Out of interest, which feature of the notebook-like output do you use, multi-cells, rst syntax, something else?

@Titan-C do you have an opinion on this one?
Out of interest, what do you use the no

**Comment by lesteve** [comment]
Also just curious, why don't you want the example to be run, because it takes too much time?

**Comment by chsasank** [comment]
Yep, don't want the example to be run because it takes too much time.

**Comment by Titan-C** [comment]
> If I understand you correctly you are saying that when an example is not executed, the output HTML doesn't have a notebook-like look (e.g. multiple cells). You are not talking about jupyter notebooks.

I'm surprised of this. Because the html rendering is done directly from
the parsed source code and you should get a notebook styled html if your
python source code has a notebook syntax, defining blocks.

I just tested on master renaming the examples from our tutorials
folder(those show up in the website as second gallery), which has
notebook styled examples syntax. They don't get executed but still
present a html notebook and let you download a jupyter notebook file
which is also split in many blocks.

>
> It feels like an oversight and a PR would be more than welcome. Out of interest, which feature of the notebook-like output do you use, multi-cells, rst syntax, something else?

I'm curious about this, which is the feature you are missing? Can you
prepare for us an example setup which we can test and understand the
behavior you expect but is not happening. Also which version of the
Sphinx-Gallery are you using?

**Comment by chsasank** [comment]
It looks like I've overlooked this. It indeed works as expected. Sorry for bothering.
