### ISSUE TITLE
NameError: name '__file__' is not defined

### ISSUE THREAD

**Issue by amueller** [sphinx-gallery/sphinx-gallery#211]
I just upgraded my ancient wordcloud sphinx setup to use sphinx-gallery. However, it seems like ``__file__`` is missing from the globals. Is that on purpose?
I want to load a file that's in the same directory as the example. Is there a better way to do that?

**Comment by Titan-C** [comment]
`__file__` is not defined because to allow for the notebook styled
examples we send chunks of code to the python interpreter and capture
the output, thus there is no notion of `__file__`.

Since at least execution is done is the same directory where the script
is located we can manually set the `__file__` variable when executing
the code chunks.
