### ISSUE TITLE
Limited rst to md support in notebooks

### ISSUE THREAD

**Issue by chsasank** [sphinx-gallery/sphinx-gallery#219]
Hi,

Current parser for rst to md in notebook.py is quite limited. For example this [page](http://pytorch.org/tutorials/advanced/neural_style_tutorial.html#)'s notebooks looks like this: 
![screen shot 2017-04-06 at 12 13 02 pm](https://cloud.githubusercontent.com/assets/9305875/24741190/928ef672-1ac2-11e7-9d03-6df09dc1d5d3.png)

Here's what I propose: use [pypandoc](https://github.com/bebraw/pypandoc) if available else fallback to current implementation. If you like this, I can raise a PR.

**Comment by lesteve** [comment]
Great to see that PyTorch is using sphinx-gallery! To be fair this is probably one of the more involved sphinx-gallery "example as tutorial" I have seen in the wild (~600 lines).

My first instinct is to be slightly reluctant to go in this direction but I could be convinced if the PR has an optional dependency on pypandoc and is not too intrusive.

The first thing to check would be that the pandoc does convert the rst to something reasonable in your example.

**Comment by chsasank** [comment]
> "example as tutorial"

Well, I moved pytorch tutorials from github hosted notebook files to html pages based on sphinx gallery. I think sphinx gallery is excellent for writing tutorials. I have a simple script [here](https://gist.github.com/chsasank/7218ca16f8d022e02a9c0deb94a310fe) to convert notebooks to notebook styled examples based on pandoc.

>  that pandoc does convert the rst to something reasonable

It works great.
![screen shot 2017-04-07 at 10 36 51 pm](https://cloud.githubusercontent.com/assets/9305875/24811293/0c7f0cb2-1be3-11e7-9119-15bef3b9f983.png)

> not too intrusive.

Here's what I want to do: edit this [function](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/notebook.py#L60) to this:

```
def rst2md(text):
    """Converts the RST text from the examples docstrigs and comments
    into markdown text for the Jupyter notebooks"""
    try:
        import pypandoc as pdoc
        return pdoc.convert_text(text, 'rst', 'md')
    except ImportError
        <Current code>
        ... 
```

That's non intrusive enough, I guess?

**Comment by chsasank** [comment]
1

**Comment by lesteve** [comment]
The change does not look too intrusive indeed. Maybe others (@Titan-C @GaelVaroquaux @Eric89GXL) have comments on this before you start working on a PR.

A small comment: note that when downloading the notebook you probably won't have `neuralstyle.png` lying around so that the image will be missing in the notebook.

**Comment by Eric89GXL** [comment]
If the proposal is to (if possible) offload the conversion onto a better-tested library, then +1 from me

**Comment by Titan-C** [comment]
The last time someone suggested using pandoc the discussion immediately ended with NO. because that includes putting the entire GHC and pandoc as a dependency. At those times we were not aware pypandoc existed nor that pandoc now can be installed as a binary.

I just tested pypandoc and it is capable to download and install pandoc in userspace, is also in conda-forge and windows wheels ship the pandoc binary. So installing this dependency becomes very easy now.
I agree on handing over as optional dependency the rst to markdown conversion to a specialized library. The try-except block is unintrusive enough for me and is the same way we support mayavi.

+1

**Comment by ambrosejcarr** [comment]
We're trying to using sphinx-gallery for our [package](https://github.com/spacetx/starfish), but running into problems where notebooks generated by sphinx-gallery don't convert properly, which has us reverting to checking in notebooks for the time being. 

Came here to +1 the issue.

**Comment by romanlutz** [comment]
As far as I can tell this problem still exists, i.e. downloading notebooks from sphinx-gallery means they have rest-formatted markdown which doesn't render properly (like in the screenshot in the first post). Does anyone have workarounds?

sphinx-gallery is such a great effort, would be a shame not to be able to use it because of this.

**Comment by lucyleeow** [comment]
@larsoner happy to implement the above proposed (optional) pypandoc solution if we're still +1

**Comment by lucyleeow** [comment]
MyST discussion continued in #710
