### ISSUE TITLE
Make example text optional

### ISSUE THREAD

**Issue by anntzer** [sphinx-gallery/sphinx-gallery#222]
I would be nice if the example text (in the example module docstring) was optional.  Of course, an example *title* is necessary e.g. to build the index (well, I guess it could always default to the filename), but requiring more text tends to lead to examples such as https://github.com/matplotlib/matplotlib/pull/8233/files, where the body of the text just paraphrases the title.

**Comment by Titan-C** [comment]
It is true we raise an error for not having a title and a first paragraph. But not having a first paragraph remains "optional" you just need to have enough whitespace (an empty line is enough). 
This works well enough:

```python
r"""
My clever example that gives no explanations
============================================

"""
import clever
```

Having said that, we do believe a text paragraph is good habit. Also the first paragraph goes to fill the tooltip in the main gallery that pops up when you hover an example thumbnail.  We might need to think about selectively deactivating that since it just looks ugly when there is no introductory paragraph for the example.

Finally, more a remark about Sphinx to comment on your matplotlib PR and totally irrelevant. Over time I have noticed that Sphinx does not seem to like to have the overline on the titles, might be specific to the theme I use but I saves me some warnings not to have those overlines.

**Comment by anntzer** [comment]
I totally agree that having a first paragraph is a good habit.  But forcing people to write filler text is not so useful :-)
Making the empty line optional would be great.

**Comment by Titan-C** [comment]
The empty line already works. Try it out.

**Comment by anntzer** [comment]
I meant not even requiring an empty line after the `===`.  But it's really not a big deal either.

**Comment by lesteve** [comment]
> I meant not even requiring an empty line after the ===. But it's really not a big deal either.

I am +1 on this, it should not be a big change PR more than welcome!

In case it does not already, something like this should just work:

```py
"""
Title
=====
"""
```
