### ISSUE TITLE
Large whitespace after TOC in a gallery

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#226]
Anyone know why this whitespace would show up in a sphinx gallery?

![image](https://cloud.githubusercontent.com/assets/1839645/25197591/75a3e3d8-24f9-11e7-9f55-998b136ab99c.png)

It seems like the div containing the TOC is being extended downward, even though nothing is actually filling that space:

![image](https://cloud.githubusercontent.com/assets/1839645/25197760/f118d852-24f9-11e7-887c-89a9871e9c72.png)

**Comment by Titan-C** [comment]
do you have a link where I can inspect the build? Although this should not be linked to Sphinx-Gallery but rather on your CSS

**Comment by choldgraf** [comment]
right now, no (it's the matplotlib documentation and it's kind of a beast to get running online).

I've got a buncha other things to debug first w/ getting it working, and then I will come back and start spot-checking these issues. Just posting them here so that I don't forget about it and in case anybody else is having the same problems.

**Comment by choldgraf** [comment]
OK I have a build here:

http://predictablynoisy.com/matplotlib/gallery/index.html

what I'm talking about is the big whitespace under the TOC for the page

**Comment by Titan-C** [comment]
I know the cause is that sphinx-gallery inserts
```html
    <div style='clear:both'></div>
```
after each section. We need that to clear the floating behaviour of the thumbnails. This does not produce any issue in separating between each example section. I tried for the Sphinx-Gallery docs to imitate matplotlib gallery having the table of contents and all examples in individual folders. But for all our supported CSS themes and even loading the matplotlib `mpl.css` I cannot get a large space after the contents.

This problem has to do with the Matplotlib html layout and style. Because if I install matplotlib's `conf.py` and `_static` and `_templates` I get the spacing after a table of contents for our gallery. I just don't know enough web development to be able to debug what in your layout is giving the conflict.

**Comment by Titan-C** [comment]
I actually know what is giving you the problem in the layout. It is your side bar. It is an element that floats to the right. Sphinx-Gallery clears that float. Notice how the next section starts just after the content of your sidebar is over.

**Comment by Titan-C** [comment]
There are only 2 official Sphinx themes that have this problem: Sphinxdoc and bizstyle. The problem is because they define the sidebar in the html before the main document and make it a float. The other themes with a table of contents at the sidebar define it after the main document. 

@choldgraf try moving https://github.com/matplotlib/matplotlib/blob/master/doc/_templates/layout.html#L54-L75 somewhere around here https://github.com/matplotlib/matplotlib/blob/master/doc/_templates/layout.html#L211

**Comment by choldgraf** [comment]
Ah that is a good find! Unfortunately the template MPL is using is messed up enough that I can't get the sidebar to locate properly unless it comes before the content, but I can find other workarounds for this (e.g. apparently if yopu put the `clear` code into a `span` block instead of a `div` block, it works fine)
