### ISSUE TITLE
backreferences_dir vs. mod_example_dir?

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#227]
I see that in the documentation online, it says that function-specific examples should go in `backreferences_dir`. However I've found other repositories that instead use "mod_example_dir". I found that the latter works for my build while the former is ignored. Which is the one that should be used moving into the future?

**Comment by Titan-C** [comment]
I recently merged PR #151. `backreferences_dir` is the
current(git-master) and to be used configuration variable, that's why
you find about it in the readthedocs documentation. `mod_example_dir` is
the old configuration style which works in the current released version
stable version(0.1.8). Once version 0.1.9 is released
`backreferences_dir` will start working, while for the moment keeping
backwards compatibility with the old config.

To avoid confusions. I'll release 0.1.9 today.

**Comment by Titan-C** [comment]
Version 0.1.9 is released and on PyPI

**Comment by choldgraf** [comment]
hehe - that is a nice way to solve this problem :)

I guess I was just looking at the wrong version of docs in that case?

Thanks!
