### ISSUE TITLE
Adding a link to Binder in examples

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#238]
A quick idea for a feature (testing the waters to see if people are friendly to it):

A quick background on Binder for those who haven't used it. The goal of Binder is to let users click a button that takes them to a live jupyter environment running off of a remote server. People use it to demo packages, ship supplementary code with papers, etc. Thus far these have existed on "mybinder.org", e.g., the [LIGO binder](http://mybinder.org/repo/minrk/ligo-binder/notebooks/GW150914_tutorial.ipynb).

In recent months the Binder project has become a little unstable because the team supporting it hasn't had time to maintain it. However, at Berkeley I've been working with some Jupyter folks to rebuild Binder's backend using JupyterHub. This means that `mybinder.org` will be a lot faster and way more stable. 

We're going to have it set up such that devs don't need to manually re-build their binder every time something is updated. It will automatically build if someone clicks a Binder link w/ a hash that differs from whatever is currently in `mybinder.org`.

Since sphinx-gallery is already generating jupyter notebooks, I think it'd be pretty easy to add a flag (e.g. `binder=True` in `conf.py`) that will automatically insert links to binder instances of examples that are built with a sphinx gallery. This could insert an image like this one:

![](http://mybinder.org/badge.svg)

At the top of the rST in each example (probably just under the title, or as a button at the bottom). When users clicked this it will dump the user into a live binder instance on `mybinder.org`.

I think it could be a really cool way to add some extra interactivity to examples with minimal extra effort on the part of devs. Are folks open to a PR that looks into doing this? (once we stabilize binder a bit more)

**Comment by Titan-C** [comment]
Yes. Binder has been inside our desired features since long ago. I have
tried it from time to time to see progress on it. My main problem is
that Binder requires a Github repository with the Jupyter notebooks and
we don't have that as an output of Sphinx-Gallery.

In the way the galleries are build and Sphinx works it is quite unlikely
that we can point Binder to any particular folder of the documentation
with the jupyter notebooks, because Sphinx moves all of them into the
_download folder.

My current vision. Is that Sphinx-gallery should produce a zip file
containing the jupyter notebooks(we do that already), and include in
this zip file the DOCKERFILE to generate the Binder instance. Then the
challenge is on the Binder side to be able to open this zip file. This
zip file will be inside _downloads, because that is the only place we
can save objects is Sphinx which are not html. And I think it has to be
a zipfile because if we make binder point to the _downloads folder of
the documentation it will find too many files and that would confuse the
users, so is better to point to a single zip file.

If the binder instance produces predictable urls we can make it so in
Sphinx-Gallery that every example has a link to the binder file to test
it. Otherwise it would have to be gallery global, and have as you point
out a badge that lets the user open the gallery inside binder.

**Comment by choldgraf** [comment]
A quick thought: what if, as an early case, we only supported documentation that is built with `gh-pages`? For this instance, all of the jupyter notebooks will be embedded in `_downloads` as you say. The version of Binder we're working on will let you point it to a specific branch of a repo, which means that we could generate links like `github.com/myname/myrepo/gh-pages/_downloads/my_notebook.ipynb`. The user would be dumped straight into that notebook, so they wouldn't see anything else of the folder that it is inside. Could be a good first-start, and then we can think of how to extend to other usecases if need be, but I bet supporting `gh-pages` would already capture many repositories.

**Comment by choldgraf** [comment]
(btw you can take a look at this version at "beta.mybinder.org")

**Comment by Titan-C** [comment]
Github pages is fine. The current main users of Sphinx-Gallery:
Scikit-learn,Nilearn,MNE-python do host the documentation in github
pages nowdays.

I tried the url, but it did not worked for me.

**Comment by choldgraf** [comment]
This one?

http://beta.mybinder.org/

I just tried it and it worked fine for me

**Comment by choldgraf** [comment]
(make sure you use http and not https, we haven't got that running yet)

**Comment by Titan-C** [comment]
Sorry I was not specific enough. Yes I can open the website. I just
can't make it work. Neither putting the nilearn github page, not even
with the official binder example
http://github.com/binder-project/example-requirements
as the repository to build
I get the message: `{"kind":"pod.phasechange","payload":"Pending"}` and
nothing happens.

**Comment by choldgraf** [comment]
ah - I bet this is because the beta page has its resources maxed out (we're keeping it limited to a few nodes so we don't burn through all our cash). I'll let you know when it's a good time to check it out, we're looking into buying more cloud resources now but need to make sure we can find some $$$ first

**Comment by choldgraf** [comment]
@Titan-C looks like it was actually a bug we introduced into Binder yesterday :-)  as I say it's in beta right now haha. Give it another shot.

**Comment by GaelVaroquaux** [comment]
Yeah!!!!

**Comment by yuvipanda** [comment]
@choldgraf now that mybinder.org is in much better shape, do you wanna pick this up?

Also @minrk has done amazing work on things like https://minrk.github.io/thebelab/ perhaps that could also be integrated here somehow?

**Comment by choldgraf** [comment]
@yuvipanda it's already almost there in #244 

right now it got bogged down in a super annoying sphinx bug that's hard to debug. I'll pick it back up after the retreat talks!

**Comment by larsoner** [comment]
@choldgraf isn't this merged now?

**Comment by choldgraf** [comment]
woot! yep!
