### ISSUE TITLE
ENH: Add thumbnail size setter

### ISSUE THREAD

**Issue by Eric89GXL** [sphinx-gallery/sphinx-gallery#277]
It looks like the thumbnail dimensions are static:

https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_rst.py#L357

I'm happy to add it as a `conf.py` key (`thumbnail_size` tuple?) if people agree it would be useful.

**Comment by Titan-C** [comment]
Thumbnails are of fixed size and rather big(compared to the gallery thumbnail size) as on scikit-learn they were used on other places in their docs(the carousel for example).

I'm not sure about adding this extra setter. But if we go for it, I might say start clustering it with other options for the thumbnail, like the default image. Something like
```python
'gallery_thumbnails':{'default': 'no_image.png', 'size': (200, 140),'broken':'broken_example.png'}
```
Of course that would break backwards compatibility. As we have the default image as a separate key. But in this way we could expose those defaults to the config rather than setting them up inside the codebase. Then this default will also be more discoverable and help with #276

**Comment by choldgraf** [comment]
It sounds like @Titan-C is suggesting that using CSS to resize images would be a decent solution, is that right?

**Comment by Titan-C** [comment]
We already resize with CSS. My guess is @Eric89GXL wants to set a new smaller size on the Thumbnail, so save on space as the thumbnail images is larger than the saved size. Otherwise, if it is on the aesthetics of the thumbnail, yes changing CSS at will is the easiest and can be done on the user side.

**Comment by Eric89GXL** [comment]
I actually just want larger images in the gallery section. If this can
already be done with CSS, then I'll just make a documentation PR update.

**Comment by choldgraf** [comment]
were you able to figure this out w/ CSS? (and if so can we close this?)

**Comment by Eric89GXL** [comment]
Will auto-close on merge

**Comment by Eric89GXL** [comment]
CSS isn't sufficient, I have opened a different bug report about that (#282). Closing this one to move discussion there.
