### ISSUE TITLE
option to control verbosity

### ISSUE THREAD

**Issue by jasmainak** [sphinx-gallery/sphinx-gallery#301]
The newer version of sphinx-gallery does not anymore print the output from the executed examples on the console. This can be problematic when some of the examples are slightly longer as Circle CI times out if there is no output for 5 minutes. 

This is what I've been facing for [autoreject](https://github.com/autoreject/autoreject/pull/82) where some of the examples are on the longer side. Granted this is not ideal and I'm working on improving the build timing, but I feel this is orthogonal to the issue of verbosity. I prefer to see the output as it also makes debugging easier.

I'm posting the issue as @larsoner mentioned he had some ideas to solve it which could be discussed here.

Thanks a ton!

**Comment by Titan-C** [comment]
We reduced verbosity because now we can separately capture failing
examples finish the build with error code. Thus our output was
unnecessarily verbose for some of our users. We also adopted the status
iterators which reduce output size even further.

The easy control on verbosity is to build with the flags '-v', '-vv', '-vvv'.
And one of those options gives you the standard output of every file.

But there was a fundamental change on how we capture the output in the
last version. Before we would pass the output through a T, log one exit
and have the other exit go to the stream buffer. Then you would have the
stdout be shown every time the buffer flushes. Now we just capture all
the output until the codeblock finishes execution. Then save that log to
build the rst file, and also send that log the Sphinx logger.

This change means, that increasing the verbosity will not help you with
the timeout problem. Since sphinx will only have the output of the block
when the code block finishes execution.

We could check if Sphinx's status iterator supports having a progress
indicator: a Slash that spins, a dot that moves back an forth. That
would keep logs short, and help with the timeout problem.

**Comment by GaelVaroquaux** [comment]
> Before we would pass the output through a T, log one exit
> and have the other exit go to the stream buffer. Then you would have the
> stdout be shown every time the buffer flushes. Now we just capture all
> the output until the codeblock finishes execution.

Well, for usage on circle the new approach is a major problem, I would
say. In effect, it implies that all examples must be shorter than 5mn,
which is not the case for projects that do major computation.

Is there a way to reenable the Tee?

**Comment by lesteve** [comment]
IIUC this is related to the change in logging that were done in https://github.com/sphinx-gallery/sphinx-gallery/pull/250. Personally I think the simplest thing to do would be just to revert them unless someone plans to fix this in the not too distant future. cc @QuLogic.

**Comment by QuLogic** [comment]
We could re-instate the `Tee` and instead of `sys.stdout`, point one output at the logger. That should have the same effect as before, but still produce output.

**Comment by jasmainak** [comment]
Would this fix the timeout problem on Circle?

**Comment by GaelVaroquaux** [comment]
> Would this fix the timeout problem on Circle?

Probably

**Comment by lesteve** [comment]
We would also need an easy way to turn the sphinx-gallery logger to verbose. Maybe doable already in conf.py, not sure.

**Comment by QuLogic** [comment]
Increasing logger verbosity can be done the same way as normal sphinx, i.e., by passing `-v` to `sphinx-build`. If you're using the default makefile, then `make SPHINXOPTS=-v html` works for that.

**Comment by lesteve** [comment]
> Increasing logger verbosity can be done the same way as normal sphinx, i.e., by passing -v to sphinx-build. If you're using the default makefile, then make SPHINXOPTS=-v html works for that.

Nice, thanks! For reference for a conf.py-only solution I found this works as well:
```py
def setup(app):
    app.verbosity = max(1, app.verbosity)
```

**Comment by lesteve** [comment]
> The newer version of sphinx-gallery does not anymore print the output from the executed examples on the console. This can be problematic when some of the examples are slightly longer as Circle CI times out if there is no output for 5 minutes.

@jasmainak as a temporary work-around it seems like you can configure the timeout without output in CircleCI. See https://circleci.com/docs/1.0/configuration/#modifiers.

**Comment by jasmainak** [comment]
> @jasmainak as a temporary work-around it seems like you can configure the timeout without output in CircleCI. See https://circleci.com/docs/1.0/configuration/#modifiers.

Thanks I already know this but I prefer to see all the output as before. Do I understand correctly that doing `make SPHINXOPTS=-v html` in the `Makefile` should also return to the old verbosity level?

**Comment by lesteve** [comment]
> Thanks I already know this but I prefer to see all the output as before. Do I understand correctly that doing make SPHINXOPTS=-v html in the Makefile should also return to the old verbosity level?

I tried with sphinx-gallery and adding `-v` to SPHINXOPTS works: the example outputs is printed on the console when generating the documentation. It may depend on your Makefile, but basically the thing you want is that `-v` gets to the sphinx-build command that gets run.

As noted in https://github.com/sphinx-gallery/sphinx-gallery/issues/301#issuecomment-335037763 the output is printed after a code block is done running (or only at the end of the example if you are not using the notebook-like syntax).
