### ISSUE TITLE
v0.1.14 release plan

### ISSUE THREAD

**Issue by choldgraf** [sphinx-gallery/sphinx-gallery#344]
It's been about 6 months since the last release, so I'd be keen on getting something new out the door. There have been several improvements, but still some things to take care of. I wanted to open this issue to make sure we have a plan for what to go in the next release.

I created a milestone and added two issues to it that need to get figured out:

https://github.com/sphinx-gallery/sphinx-gallery/milestone/7

Anything else that should go in there before the next version?  @Titan-C @lesteve @GaelVaroquaux @larsoner ?

**Comment by Titan-C** [comment]
Let's include PR #307. It starting from changes in our config, it's
better to keep solving these on each release.

**Comment by choldgraf** [comment]
I think it's a good idea!

**Comment by lesteve** [comment]
I agree it'd be nice to have a release soonish, be it only to push the binder functionality to sphinx-gallery users.

**Comment by lesteve** [comment]
So this has been a month already ... here are the two main things I have on my radar:
* improve floating download links. My bias is to get rid of it and use something simpler. I have started to work on this already and will let you know when I have something working.
* have .ipynb organization that mirrors the examples folders. This was part of https://github.com/sphinx-gallery/sphinx-gallery/issues/353. I am hoping that we can just copy the file ourselves in sphinx-gallery rather than relying on the `:download:` directive. This may be way too naive but this may also just work.

Also @Titan-C if you have personal notes about how to to a sphinx-gallery release, it would be great to add to the docs somewhere, just in case someone else than you needs to do a sphinx-gallery release one day ;-).

**Comment by choldgraf** [comment]
+1 to the ipynotebooks mirroring the examples tructure

+100 to de-bus-factoring sphinx-gallery releases :-)
--

**Comment by choldgraf** [comment]
hey all - I think that we are ready to cut a new release (at least judging from the items that were on our milestones). What do you all think?

**Comment by choldgraf** [comment]
cc @Titan-C in case he wants to write up some short docs on cutting a release for sphinx-gallery

**Comment by Titan-C** [comment]
The "how to release" docs where already merged in #360

**Comment by lesteve** [comment]
Fine with me!

**Comment by choldgraf** [comment]
@Titan-C nice! I didn't know it had already been merged :-)

Woo, 🚢 :shipit:

**Comment by lesteve** [comment]
If it is not too much work, it would be nice to move the documentation to CircleCI https://github.com/sphinx-gallery/sphinx-gallery/pull/327.

**Comment by lesteve** [comment]
To be honest, I don't want to delay the release too much because it has been quite a while since the last release. So if the CircleCI doc is too much work (say more than 1 day) we can release as is and do another release in a few weeks.

**Comment by choldgraf** [comment]
@lesteve do you have the time to move the docs to circleci in less than 1 day? :-)

**Comment by lesteve** [comment]
I was hoping to get some feed-back from @Titan-C to understand more what is involved and we *need* to do it before the release.

**Comment by choldgraf** [comment]
The issue you linked is for moving to github pages, which I think is orthogonal from whether to use circle or travis, no?

**Comment by larsoner** [comment]
I can try today, we do it in MNE

>

**Comment by lesteve** [comment]
> The issue you linked is for moving to github pages, which I think is orthogonal from whether to use circle or travis, no?

The question I had in mind (probably my earlier statement was too ambiguous): do we want to set-up `doctr` (or a similar tool) to move our doc to sphinx-gallery.github.io and shut down readthedocs before the release.

More details: we are already using CircleCI to build the documentation on each commit and push it to sphinx-gallery.github.io. This is the way forward to have binder support since we need the generated notebooks in the repo. On top of that I think it would be nice to use `doctr` (or a similar mechanism) to have the documentation for at least the latest release and master.

**Comment by choldgraf** [comment]
I'm +0 on this, since it is both adding complexity (adding doctr to build the documentation) and removing complexity (no more need to worry about how it looks on readthedocs). it's also adding features (more flexibility building with doctr) and removing features (no more auto-generated docs for different versions)

**Comment by Titan-C** [comment]
We don't really need to have the docs migration prior to doing the release. I did not put that PR as a blocker. I'm fine preparing a release today.

Few comments on the docs.  
- We already build them on CircleCI and push to the github pages, which we need for binder support. Because the binder team never prioritized the upload of a zip file to configure the binder instance, to my knowledge, they as for now want a github repo as the source.
- On the other hand, the binder functionality totally works on the read the docs documentation. Binder queries the github repo, not readthedocs website. So the links to the binder instance since they are statically generated and point to the github pages source repository, not even to the published website totally work from any website.
- It would be good nevertheless to move to github pages because the docs built on CircleCI include the mayavi examples, which readthedocs does not support.
- We do want to use something like `doctr` to generate the docs for the stable releases and master ond the github pages docs, something we get for free on readthedocs. `doctr` is focused on building docs on travis, I don't know how easy is to migrate to CircleCI which we like best.
- I wouldn't shut down the readthedocs website. It had made a lot of progress in online ranking and search-ability. My idea is to update all links to make the migration towards github pages simpler. I think also about giving the docs a base address to github pages, then at least the master version of the docs on readthedocs should point on every link to github.

**Comment by Titan-C** [comment]
Extra thought. Once we implement the docs for multiple version tags on github pages. We will need to include support for that in the binder links, which my guess now is we don't support that yet.

**Comment by lesteve** [comment]
> On the other hand, the binder functionality totally works on the read the docs documentation.

Right, for some reason I thought that the binder links would not be shown on readthedocs. I think this is good enough for now!

**Comment by Titan-C** [comment]
I'm going to do release 0.2 instead of 0.1.14. We have fixed a lot of things in the last 8 months, and included great features. Release commit is on https://github.com/Titan-C/sphinx-gallery/commit/3b719ca354c75e27952bbd61c16b35232ba058d4 if CI is all green I'll push to master and then upload to PyPI

**Comment by Titan-C** [comment]
Ok. All green. This is done. Github release and published in PyPI

**Comment by GaelVaroquaux** [comment]
Congratulations team! Someone does a nice tweet? So that we can retweet it. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by choldgraf** [comment]
how's this: https://twitter.com/choldgraf/status/1004086721859014656 ?

**Comment by lesteve** [comment]
Great, thanks a lot everyone!
