### ISSUE TITLE
matplotlib inline vs notebook

### ISSUE THREAD

**Issue by CompPhysChris** [sphinx-gallery/sphinx-gallery#388]
Currently sphinx-gallery puts ["% matplotlib inline"](https://github.com/sphinx-gallery/sphinx-gallery/blob/830a11c6ba5a80a4cbbaff7e2932dd37e81321a5/sphinx_gallery/notebook.py#L113) at the top of all notebooks.  Would it be possible to add an option to use "% matplotlib notebook" instead?  Interactive elements in figures seem to work better with notebook.

**Comment by lesteve** [comment]
A configurable `notebook_preamble` (or a better name) would make sense I guess.

I don't remember, does `%matplotlib notebook` work fine with JupyterLab?

**Comment by choldgraf** [comment]
cc @tacaswell - I believe that if we put `% matplotlib notebook` in the generated notebooks, then all of the matplotlib interactive examples would work, yeah?

**Comment by choldgraf** [comment]
@lesteve I believe it works now judging from this issue: https://github.com/matplotlib/jupyter-matplotlib/issues/9#issuecomment-403303690

**Comment by lesteve** [comment]
It'd be good to double-check on a relased JupyterLab version, the last comment seems to mention JupyterLab from master.

**Comment by choldgraf** [comment]
true - though note that currently JupyterLab needs to be turned on manually with sphinx-gallery, so probably a small number of people are using it. My guess is that the next JupyterLab release (probably several) will happen before the next SG release

**Comment by tacaswell** [comment]
To work with lab you will have to use ipympl (`%matplotlib widget`) to work in JLab.

**Comment by choldgraf** [comment]
ah good point - I believe that in general `%matplotlib notebook` is deprecated in favor of `%matplotlib widget`

**Comment by choldgraf** [comment]
> In general, sphinx-gallery should not make any assumptions on what users want or need. 

the problem is that making fewer assumptions about what people want also means exposing a more complex API for users to wrap their heads around. In a sense, precisely the thing that tools like sphinx-gallery provide is an opinionated, pre-configured pathway to deploy something that's "good enough" for 80% of use-cases.

In this case, I'm open to the idea of making this a configurable field that defaults to `%matplotlib inline`. I think it'd just be a matter of changing:

https://github.com/sphinx-gallery/sphinx-gallery/blob/5d0588f595d180c8d22429ed9dc1457b63e01392/sphinx_gallery/notebook.py#L113

to something like `add_code_cell(work_notebook, gallery_conf['custom_cell'])`

**Comment by choldgraf** [comment]
I just opened up #401 which would let you put whatever text you like in that first notebook cell :-)
