### ISSUE TITLE
Wish: IPython Notebook Download

### ISSUE THREAD

**Issue by florian-wagner** [sphinx-gallery/sphinx-gallery#39]
Since documenting strings are possible since PR #36. A possible feature would be an optional "Download as IPython Notebook" button for example scripts, when an IPython installation is found.

**Comment by jnothman** [comment]
Unfortunately jupyter supports markdown natively, but not restructured text

**Comment by florian-wagner** [comment]
I see, haven't thought about that. But it should be possible the other way round, i.e. allowing and integrating plot_example.ipynb files in examples folder.

**Comment by lesteve** [comment]
Obviously this, or a variant of this, is something we'd like to do at some point in the future. 

There are multiple approaches but I think we want to keep examples as plain python files that are convertible into IPython notebooks (for example through simple markup), rather than allowing .ipynb examples.

**Comment by GaelVaroquaux** [comment]
We now have notebook-style examples (which are awesome!). It's the first step to have IPython notebooks. @lesteve, @Titan-C any idea of the timeline for that?

http://sphinx-gallery.readthedocs.org/en/latest/tutorials/plot_notebook.html#sphx-glr-tutorials-plot-notebook-py

**Comment by Titan-C** [comment]
closed with #75
