### ISSUE TITLE
Unnecessary regeneration of API docs

### ISSUE THREAD

**Issue by jnothman** [sphinx-gallery/sphinx-gallery#394]
The creation of `.examples` files for backreferences from API documentation always leaves those `.examples` newly modified, even if the underlying examples were unchanged. This results in the API doc being re-generated as well (i.e. they are marked as changed in Sphinx's "updating environments" log item).

Ideally, we should have a way to identify unchanged examples backrefs, and make sure their mtimes are unchanged. One way may be to write to a temporary file and only overwrite if changed, after all examples are run.

But I remember implementing the backrefs `.examples` files was a bit of a hack, so I'm not sure how easy it is to hack it further!

**Comment by jklymak** [comment]
OK, I'd be willing to poke at this, because this re-generation drives me nuts for matplotlib dev docs; basically one small change still takes 10 minutes to rebuild the webpage locally.  

But, I wasn't quite clear how to install the development version of sphinx-gallery and be able to edit the source and execute it on the fly.  Is there a guide somewhere (or is it a sign that if I can't figure that out, I should just steer clear :wink:)

**Comment by larsoner** [comment]
> But, I wasn't quite clear how to install the development version of sphinx-gallery and be able to edit the source and execute it on the fly

I would do this the way it can be done with most (pure) Python repos:
```
python setup.py develop
```
Or you can do
```
pip install -e .
```
https://stackoverflow.com/questions/30306099/pip-install-editable-vs-python-setup-py-develop

**Comment by jklymak** [comment]
Yeah, thats what I do for matplotlib, but I must have done something wrong w/ `sphinx-gallery`.  Just wasn't sure if there were extra incantations...
