### ISSUE TITLE
feature request: only rebuild individual examples

### ISSUE THREAD

**Issue by amueller** [sphinx-gallery/sphinx-gallery#397]
I want to debug an example that's breaking when run via sphinx-gallery but not by itself.
However, that requires running all examples, which takes forever in scikit-learn.

It would be great if I could generate single examples to debug them.
Sorry if that's already possible, haven't seen it in the docs.

**Comment by Titan-C** [comment]
Sphinx-gallery only rebuilds the examples that have changes since the
last build.

But you can also use the filename pattern to specify which example you
want to build during debugging.

https://sphinx-gallery.github.io/advanced_configuration.html#parsing-and-executing-examples-based-on-matching-patterns

**Comment by amueller** [comment]
well the last build might have been a long time ago, though ;) Or I might be on a completely different branch.
I guess changing the configuration would be an option. I was more thinking about it as running a specific test instead of running all tests, so I was imagining a command line option or something like that. Maybe that's too specific though?
I couldn't reproduce the original bug that prompted this, maybe just running the examples is enough to debug.

**Comment by larsoner** [comment]
> I was more thinking about it as running a specific test instead of running all tests, so I was imagining a command line option or something like that

This sounds like what @Titan-C was referring to with the link to the docs above -- it allows specifying which examples to run using a regular expression. And you can do it from the command line (it's at the bottom of the sectino in a `.. note::`) because you can override `conf` options via the command line.

**Comment by amueller** [comment]
Sorry I read too fast! Thanks!
