### ISSUE TITLE
Allow .rst extension for README files

### ISSUE THREAD

**Issue by banesullivan** [sphinx-gallery/sphinx-gallery#508]
https://github.com/sphinx-gallery/sphinx-gallery/blob/cd6eaed237b00ed505b3faa095694c2d66afe49d/sphinx_gallery/gen_gallery.py#L272

Currently, SG forces the required README files to have the `.txt` extension. I imagine almost every project using SG is formatting these README files in RST so allowing an `.rst` extension makes sense.

Why does this matter? It makes viewing the example directory on GitHub a bit more user-friendly as GitHub will render RST properly when the file has an `.rst` extension. See this page for example: https://github.com/pyvista/pyvista/tree/master/examples

A newcomer to the project might explore the example directory in the repo before heading to the gallery on the docs and I'd much rather have a rendered page there than unwelcoming, raw RST

**Comment by banesullivan** [comment]
Realizing now that this is a duplicate of #223

**Comment by larsoner** [comment]
@banesullivan this one seems pretty straightforward, look for `README.txt` then `README.rst` in a loop, break on find, `else` raise error instead of the current pattern (if README.txt not found, raise error). Can you make a PR? You can change `sphinx-gallery/tests/tinybuild` to have `README.rst` to make sure it works.

**Comment by banesullivan** [comment]
Thanks for the tip, @larsoner! I'll toy with this and try to get PR in my free time this week
