### ISSUE TITLE
Linking to external examples

### ISSUE THREAD

**Issue by banesullivan** [sphinx-gallery/sphinx-gallery#519]
I've been wanting a way to create a gallery with thumbnails like what SG creates that will show images and link to external websites. For example, in PyVista, we have a [gallery of examples built using SG](https://docs.pyvista.org/examples/index.html) and a [separate page next to that of "External Examples"](https://docs.pyvista.org/external_examples.html). Right now, that list of external examples is quite boring. Ideally, I would like a nice gallery just like what SG produces that would link to those external sites such that when the user hovers over the thumbnail it'd show a description.

This is totally different than typical examples in that there's no code; only PNGs, a one-line description, and a weblink. I'm curious if it'd be possible to make this sort of gallery using SG?

**Comment by GaelVaroquaux** [comment]
> I'm curious if it'd be possible to make this sort of gallery using SG?

I would create it via the README.txt file in the folder, putting the
correct code to generate it. You can have a look at a generated index.rst
to have an idea of what kind of code sphinx-gallery uses.

**Comment by banesullivan** [comment]
It took a while for me to get around to it but it was super easy! Thanks for the tip on looking at the generated index.rst file - it had just what I needed. In breif, simply make an entry as:


```
.. raw:: html

    <div class="sphx-glr-thumbcontainer" tooltip="3D visualization for the Open Mining Format (omf)">

.. only:: html

    .. figure:: ./images/external-examples/omfvista.png
       :target: https://opengeovis.github.io/omfvista/examples/index.html

       3D visualization for the Open Mining Format (omf)


.. raw:: html

    </div>


.. toctree::
   :hidden:

   3D visualization for the Open Mining Format (omf) <https://opengeovis.github.io/omfvista/examples/index.html>


```

Which will display an image that will link to an external site and it will appear in the TOC:


![Screen Shot 2019-08-31 at 4 42 45 PM](https://user-images.githubusercontent.com/22067021/64069786-65bcef00-cc0e-11e9-8f78-401364fcc459.png)


I just pushed this to the PyVista docs: https://docs.pyvista.org/external_examples.html which should be live before long


Unfortunately, I'm getting a weird offset in the gallery shown in the image above. Any ideas on how to fix that?

**Comment by larsoner** [comment]
I usually find these are CSS problems, and diagnose them in Chrome developer mode.

In this case if I interactively change `.sphx-glr-thumbcontainer` to have `min-height: 250px` instead of `230px` things look correct. If I go down to `200px` they get worse (only 2 items in the second row, and they are pushed to the right). No idea why because I am no CSS expert. But hopefully it gives you some way to work toward a fix. If you don't want to diagnose anymore, perhaps just override the CSS in your own custom file setting it to 250px.

It might be because in SG we set the thumbnail size somehow to be good/usable by the CSS, and by using your own image from somewhere else it's not sized properly. So resizing your external image thumbnail might also fix it.

In any case, closing since this sounds solved (aside from CSS tweaks and/or image size fixes).

**Comment by GaelVaroquaux** [comment]
Maybe we could improve the documentation to point to browsers developer modes. 

⁣Sent from my phone. Please forgive typos and briefness.​
