### ISSUE TITLE
No way to prevent insertion of inlined SVG images, and instead insert raw HTML

### ISSUE THREAD

**Issue by kchawla-pi** [sphinx-gallery/sphinx-gallery#531]
Sphinx-Gallery version used: 
 - 0.4.0
- latest version compatible with Python 3.6

We are working on [GLM Reporter](https://github.com/nistats/nistats/pull/352) . The feature takes some args and generates a report, which contains many inlined SVG images. The entire report is a string, including the code for the generated SVG images. 

This string is wrapped as HTMLDocument object ([nilearn.plotting.js_plotting_utils.HTMLDocument](https://github.com/nilearn/nilearn/blob/bfbc2632f90e7e8e3ee3b7036d4fd08d8ec91fec/nilearn/plotting/js_plotting_utils.py#L89)).

When we run `make html` on this, the GLM Reporter function is executed, and all the images created as SVG's (they are not saved to disk by the feature) are saved to disk and inserted into the HTML.

The HTML code, which we would want inserted, perhaps as an iframe, is not.

I have bundled the 4 files I think are pertinent to demonstrate what I am saying and maybe help reproduce & troubleshoot. This includes the `.py` source, the `.rst` and `.html` generated by Sphinx-gallery, as well the report this PR creates, containing the HTML we would like inserted into the gallery example.

The source `.py` file for the example is also at https://github.com/nistats/nistats/blob/43ebb718619a0e5021d7faa3a12c090cc5f7177e/examples/02_first_level_models/plot_adhd_dmn.py

The section I speak of is right at the bottom of the page.

Is there anyway to do one or the things we want without editing the raw html generated? 

Attached:

[example-files.zip](https://github.com/sphinx-gallery/sphinx-gallery/files/3529282/example-files.zip)

**Comment by larsoner** [comment]
Have you looked at the "custom scraper" docs?

https://sphinx-gallery.github.io/advanced.html#custom-scraper

Somewhat close to what you want to do (I think?), I made a custom scraper that took a `html` file generated by a script and embedded it using `iframe`:

https://github.com/mne-tools/mne-python/blob/master/mne/report.py#L2085
https://github.com/mne-tools/mne-python/blob/master/doc/conf.py#L349-L350
https://github.com/mne-tools/mne-python/blob/master/doc/conf.py#L380-L382

Output (look for "The HTML document written by mne.Report.save()"):

https://mne.tools/dev/auto_examples/visualization/plot_make_report.html#sphx-glr-auto-examples-visualization-plot-make-report-py

**Comment by GaelVaroquaux** [comment]
The problem here seems rather to be that sphinx-gallery is inserting things that it should not be. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by larsoner** [comment]
> The problem here seems rather to be that sphinx-gallery is inserting things that it should not be.

> The HTML code, which we would want inserted, perhaps as an iframe, is not...

> ...as well the report this PR creates, containing the HTML we would like inserted into the gallery example.

So you want a HTML iframe instead of the standard Scraper image, right?

If so, that's exactly what my ReportScraper does. The only place SG inserts an image in my ReportScraper example is in the gallery page containing links to individual examples, indeed currently you cannot change this to anything other than a single image linking to a page for the example. In the actual rendered example page, though, ReportScraper inserts an iframe with HTML content (no MPL/Mayavi figures), which sounds like what's being described. And based on what was linked in the ZIP (just a renderede-example HTML file, not the gallery page) it also sounds like I've already described what you want.

@GaelVaroquaux did you look at the example output I linked to to see if it's close to what you want?

https://mne.tools/dev/auto_examples/visualization/plot_make_report.html#sphx-glr-auto-examples-visualization-plot-make-report-py

**Comment by kchawla-pi** [comment]
Thanks @larsoner I will check out the custom scraper.

Some new development, the inadvertent insertion of images is happening in Jupyter notebooks as well, so this might not be due to sphinx-gallery alone or at all.

![image](https://user-images.githubusercontent.com/8203204/63525547-2dc2f700-c4fe-11e9-9109-ecbb3ff62c0c.png)

**Comment by kchawla-pi** [comment]
It sometimes happens on manually created notebooks and sometimes not. This is weird. I will try the custom scraper for sphinx-gallery for the docs. I dunno why this image thing happens.

**Comment by kchawla-pi** [comment]
Force closing each plot right after to has been written as an SVG string stopped the insertion of images.  Now trying it with doc buld.

**Comment by larsoner** [comment]
In theory you can just do `image_scrapers=()` (see [here](https://sphinx-gallery.github.io/configuration.html#image-scrapers)) if you don't want SG to find/process the images. This combined with your own custom scraper looks like what you want.

**Comment by kchawla-pi** [comment]
Force closing it manually also prevents this from happening in Jupyter Notebooks as well so I will do that. I'll try the custom scraper. Thanks so much!

**Comment by kchawla-pi** [comment]
Woohoo! The images were not inserted in the examples! Now to insert the report with your suggestion.

**Comment by larsoner** [comment]
In theory it should be quite easy since you have the ability to get the embedded `iframe` directly. I couldn't do that over in MNE because the JavaScript in the embedded one interacted poorly with the JS in the main site unless it was in a separate HTML file for some reason. So you can probably skip the `copy-files` steps in the MNE repo.

**Comment by larsoner** [comment]
FYI this was the whole PR originally (has some styles that might help you tweak things)

https://github.com/mne-tools/mne-python/pull/6433/files

**Comment by larsoner** [comment]
I commented over on your PR, you need to modify `sphinx_gallery_conf`. I'll close this since I think no action is needed from the SG end, but feel free to reopen if something ends up missing.
