### ISSUE TITLE
python warning when "print(__doc__)"

### ISSUE THREAD

**Issue by agramfort** [sphinx-gallery/sphinx-gallery#55]
We use `print(__doc__)` everywhere in examples and this generates now :

```
Built-in functions, exceptions, and other objects.

Noteworthy: None is the `nil' object; Ellipsis represents `...' in slices.
```

See for example in:

http://martinos.org/mne/dev/auto_examples/plot_extract_events_from_raw.html#sphx-glr-auto-examples-plot-extract-events-from-raw-py

Can we avoid this? The reason for the `print(__doc__)` is that when running the script from the terminal it prints the doc.

**Comment by lesteve** [comment]
I can reproduce this. It seems this is `__builtin__.__doc__` somehow making its way in the output of the script rather than the module `__doc__`, probably because of the way we exec the script.

Also I seem to remember that there was some code in the scikit-learn gen_rst.py to strip the module `__doc__` from the script output since the reST docstring was already inside the html but I couldn't find it in sphinx-gallery.

**Comment by Titan-C** [comment]
So this one is a bit tricky.
Now that we slice the script by blocks the docstring is just absent when running the script. So you get something from automatic generation.
I guess your use case is the reason for this
https://github.com/scikit-learn/scikit-learn/blob/master/doc/sphinxext/gen_rst.py#L867-L872
Which was unclear and unnecessary to me when refactoring.
My quick fix would be to change
https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinxgallery/gen_rst.py#L478
into something like
```python
example_globals = {'__doc__': ''}
```
I have not tested.
But this would be too specific to usecase

**Comment by agramfort** [comment]
+1 for globals trick
