### ISSUE TITLE
Mayavi example cannot run in binder

### ISSUE THREAD

**Issue by tkoyama010** [sphinx-gallery/sphinx-gallery#554]
Hello. Thank you for great example of sphinx and jupyter. 
I couldn't import mayavi in binder. Do you know the reason?
![キャプチャ](https://user-images.githubusercontent.com/7513610/67211237-6119f780-f455-11e9-9cac-48f1521a962f.PNG)

**Comment by lesteve** [comment]
I think at the moment `requirements.txt` is used by binder. `requirements.txt` does not list mayavi. This is reasonable because when you want to work on `sphinx-gallery` you do not need `mayavi` most of the time.

We could add `.binder/requirements` or `.binder/environment.yml` to have mayavi installed inside binder. PR more than welcome!

**Comment by lesteve** [comment]
Having said that, I have no idea whether mayavi can work in a remote Jupyter server environment ... i.e. if there is an equivalent of `%matplotlib inline` for mayavi.

**Comment by tkoyama010** [comment]
Thank you for your comment. This repository may be helpfull. I'll be PRing.
https://github.com/mne-tools/mne-binder

**Comment by larsoner** [comment]
Sounds like there is a solution here, so let's go ahead and close. But @tkoyama010 if you see some room for doc improvements here in sphinx-gallery feel free to make a PR
