### ISSUE TITLE
Add a "template", to make it easy to get started 

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#555]
Following this tweet (which I haven't had time to investigate)
https://twitter.com/mybinderteam/status/1177982004643676160?s=09
I think that we might be able to make it easier for people who start from scratch with sphinx-gallery.

**Comment by choldgraf** [comment]
That does indeed sound useful to me as well. Perhaps one or more of:

1. A github template-style repository
2. A cookiecutter website
3. A CLI that generates a skeleton examples folder + configuration file that will work with SG
4. Documentation along the lines of "You've already got a sphinx website, here are the steps to add sphinx-gallery to it".

If you have questions about the templates re: Binder, I'm happy to chat about them. I've been involved with those example repositories for a while (and was the one that converted them to github templates, it was surprisingly easy)

**Comment by lucyleeow** [comment]
I'm happy to tackle 

>     1. A github template-style repository

I can make a new sphinx-gallery-template repo and make PR into it. Would this be the correct procedure?

**Comment by larsoner** [comment]
Sounds like a good plan of action to me. Though to reduce confusion, I actually wouldn't put `sphinx-` in the name. It makes it clearer what is going to be `sphinx` / `sphinx-gallery` config versus what would be done to document a sample project. Maybe `example-project`, `sample-project`, or `template-project` that documents a module `example/sample/template_project` and its examples? I think that's the most common use case and it's easy for people to `git grep example/sample/template_project` to find things to replace.

I think overall I prefer `sample-project` because I don't think the name "sample" shows up often in Sphinx/SG so it's easy to search+replace.

**Comment by lucyleeow** [comment]
I think this can be closed by https://github.com/sphinx-gallery/sample-project
