### ISSUE TITLE
Documentation is ahead of current release

### ISSUE THREAD

**Issue by lucyleeow** [sphinx-gallery/sphinx-gallery#559]
Currently documentation is built from master, meaning that the documentation is updated for new features not available in the current release. This can cause confusion ([esp for big changes](https://github.com/sphinx-gallery/sphinx-gallery/pull/541#issuecomment-552217045)).

Maybe we can update documentation with releases (like some other projects)?

**Comment by larsoner** [comment]
That would be great but it will require some infrastructure updates. @lucyleeow feel free to tackle this if you have time

**Comment by choldgraf** [comment]
This is one of the benefits of readthedocs (which can build against multiple versions of software, and can default to either the latest *stable* version, or the master branch). I suppose that ship has sailed though?

**Comment by GaelVaroquaux** [comment]
> I suppose that ship has sailed though?

We tried. Debugging the builds was harder (Mayavi ;) ).

Doesn't mean that the ship can't come back. We need to be pragmatic.

**Comment by choldgraf** [comment]
oooh right, Mayavi...

![](https://media.giphy.com/media/3oKHWvUUMPQhCOCT72/giphy.gif)

**Comment by lucyleeow** [comment]
You'll have to catch me up - what was the problem with Myavi...?

**Comment by GaelVaroquaux** [comment]
> You'll have to catch me up - what was the problem with Myavi...?

It's a long story. It's hard to install, and requires an X environment.

And, I am one of the original authors, so we love to make jokes on it.

**Comment by larsoner** [comment]
One probably easier option is to maintain `dev` and `stable` docs only. This is fairly easy to do with CircleCI currently pushing docs because you "just" triage based on whether you're on a `maint` branch (or tag or whatever) or `master` build. We could have https://sphinx-gallery.github.io/ redirect to https://sphinx-gallery.github.io/stable (probably using a `.htaccess`), and people who want to look at the latest stuff look at https://sphinx-gallery.github.io/dev

This is probably a dozen lines changed for us in `.circleci/config.yml`, plus some little HTML updates. I can do this fairly quickly if people think it makes sense. It seems easier than going back to RTD.

**Comment by choldgraf** [comment]
> It's a long story. It's hard to install, and requires an X environment.

To be fair, I also love Mayavi in the way that I love a pain-in-the-butt friend that always makes trouble but we go way back so I can't stop being friends with them. I want to stay in touch with them, just don't want to hang out every day :-)

> This is probably a dozen lines changed for us in .circleci/config.yml, plus some little HTML updates. I can do this fairly quickly if people think it makes sense. It seems easier than going back to RTD.

I think this is a nice compromise, and I agree is easier than re-tooling around RTD

**Comment by GaelVaroquaux** [comment]
> To be fair, I also love Mayavi in the way that I love a pain-in-the-butt friend that always makes trouble but we go way back so I can't stop being friends with them. I want to stay in touch with them, just don't want to hang out every day

Are you talking about me?
