### ISSUE TITLE
greedy backreferences

### ISSUE THREAD

**Issue by emmanuelle** [sphinx-gallery/sphinx-gallery#580]
I'm puzzled by two points related to backreferences, which have been introduced by version 0.5 of sphinx-gallery:
- it seems that intersphinx links are generated not only for functions or class constructors, but also for instances of objects of modules selected for backreferences. For example in https://sphinx-gallery.github.io/stable/auto_examples/plot_3_capture_repr.html#sphx-glr-auto-examples-plot-3-capture-repr-py integer variables have links to the Python doc, or in https://sphinx-gallery.github.io/stable/auto_examples/plot_0_sin.html#sphx-glr-auto-examples-plot-0-sin-py numpy arrays also have links. Is this done on purpose? With this behaviour example pages become very busy with links (see for example https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_rgb_to_hsv.html#sphx-glr-auto-examples-color-exposure-plot-rgb-to-hsv-py)
- modules listed in the `intersphinx_mapping` variable of `conf.py` seem to generate backreferences even if they are not listed in SG's `reference_url` dict. This was not the case with version 0.4.

I tried to track down when the change appeared, maybe it's https://github.com/sphinx-gallery/sphinx-gallery/commit/3acd37b716bc5684da0f4f4d7054e2ca0f3d66d8#diff-33215ef937b7c3d86fe0a23425c585e4 but I'm not sure. Happy to dig more if needed but I'd like to know first whether this is a desired behaviour or not.

**Comment by lucyleeow** [comment]
Just FYI I think this is related to https://github.com/scikit-learn/scikit-learn/issues/15812 

@lesteve advised that you can disable with:

```
sphinx_gallery_conf = {
    ...
    'inspect_global_variables'  : False,
 }
```

There is some discussion here: https://github.com/scikit-learn/scikit-learn/pull/15844 about how the purpose was to creat more relevant mini-galleries, but I think people agree that it makes the code block look busy.

**Comment by emmanuelle** [comment]
Thank you @lucyleeow ! I had a quick look through the SG issue tracker but I didn't think of looking at the scikit-learn one :-). Thanks to your suggestion I could fix the issue. I guess inspecting global variables is interesting in particular when calling methods of class instances, but maybe the level of granularity could be changed (for example inspecting global variables only for certain packages -- I'm thinking of the package being documented). 

Thanks again, and feel free to close this issue as my problem is solved :-).

**Comment by emmanuelle** [comment]
Oh and this is already documented https://sphinx-gallery.github.io/stable/configuration.html#references-to-examples I hadn't seen it.

**Comment by larsoner** [comment]
If the style / busy appearance / aesthetics is the only real problem, we could think about giving the references CSS class names based on their module names like sg-backref-python and sg-backref-sklearn (plus each gets a global sg-backref) based on which package they're from. Then you can blacklist/whitelist HTML styles of the links as you wish.

**Comment by GaelVaroquaux** [comment]
Should we not vary the style depending on whether they are instances or
the class itself? Ie have a visual appearance that is similar to the
prior behavior, but show a light hint (on hover) that there are
additional links?

**Comment by larsoner** [comment]
I would rather not change CSS by default but also add more CSS class like sg-backref-instance, sg-backref-class, etc. I know for MNE having the instance links highly visible is helpful and was a big point of adding the links in the first place. Making classes and their instance links appear differently would not be helpful in all (or most?) cases.

**Comment by GaelVaroquaux** [comment]
> I know for MNE having the instance links highly visible is helpful and
> was a big point of adding the links in the first place.

But we now have several instances of people complaining (I am not sure
that I agree with them, but I go with the flow).

The default appearance should be consensual.

**Comment by larsoner** [comment]
> The default appearance should be consensual.

Agreed. Who else has complained other than `sklearn`?

In `sklearn`'s case the busyness seems to mostly have to do with instances-other-than-sklearn (like numpy or python builtins), which would be better fixed/configurable by the `sg-backref-module-sklearn` idea, since it wouldn't break links for instances-that-are-from-sklearn.

Thinking of another module, I suspect `matplotlib` would prefer instances-that-are-from-matplotlib still being visible, because things like:
```
fig = plt.figure()
```
will link to the `fig` page, which is helpful rather than distracting (I would assume).

But if people disagree about this, or I'm misunderstanding, we can definitely change the defaults. But let's at least start with adding `sg-backref-module-sklearn` (et al.) and `sg-backref-type-class` (et al.) to make it configurable for people, since it seems like we'll want them regardless of what defaults we choose.

**Comment by emmanuelle** [comment]
> Agreed. Who else has complained other than `sklearn`?

Me :-) (for the `scikit-image` project). Pages like https://scikit-image.org/docs/dev/auto_examples/color_exposure/plot_rgb_to_hsv.html#sphx-glr-auto-examples-color-exposure-plot-rgb-to-hsv-py are too busy IMO. I'm happy with setting the option explicitly though.

**Comment by larsoner** [comment]
Ahh the link above is `scikit-image`, not `sklearn`. So that is a couple of complaints at least.

I think either way people will need custom CSS to get instances-from-my-package to look different from instances-from-other-packages. I guess the question is whether it's better to:

1. Disable instance link visibility by default in `sphinx-gallery` and have people whitelist their instances in their CSS, or 
2. Have people implement disable-by-default and whitelist their own instances.

(1) is less work for other packages I suppose. One risk is that people might not realize they *can* link to their own instances very easily. But I guess if we document it clearly enough it's okay.

**Comment by GaelVaroquaux** [comment]
>     The default appearance should be consensual.

> Agreed. Who else has complained other than sklearn?

Didn't skimage just complain?  @emmanuelle?

**Comment by larsoner** [comment]
I can take a stab at implementing the CSS classes in the next couple of days
