### ISSUE TITLE
Cell marker causes pycodestyle error

### ISSUE THREAD

**Issue by mikofski** [sphinx-gallery/sphinx-gallery#608]
I was wondering why [`#%%` is recommended](https://sphinx-gallery.github.io/stable/tutorials/plot_parse.html#sphx-glr-tutorials-plot-parse-py), because stickler-CI complains that it doesn't satisfy pycodestyle because there's no space after the comment marker. I hate to be pedantic (["... hobgoblin of little minds."](https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds)) but we depend on the CIs to review PRs so if there's an exception it's more challenging to review, sorry.

I'm really sorry if this issue is redundant. I looked through the existing issues searching for "cell" & "space" but couldn't find a relevant issue. I am just getting started with Sphinx gallery, and it's really awesome, thanks so much.

 Thanks!!!

**Comment by lucyleeow** [comment]
I think I just wanted to say 'consistently use either `#%%` or `# %%`' but decided on advising to use only `#%%` because it was simpler. I looked into the 'code block' markers used by various text editors (e.g. jupytext, pycharm etc) to find the marker used more frequently but it was pretty evenly split. I think I went with `#%%` because that was used in the original sphinx gallery issue. Also I realise now why Eclipse's automatic code formatting changes `#%%` into `# %%`

Happy to change the documentation to advise to 'consistently use either `# %%` or `#%%`' - are interested in making a quick PR for this? The file to amend is [`plot_parse.py`](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/tutorials/plot_parse.py)
