### ISSUE TITLE
Mention the multiple possible separators in the notebook-style example

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#611]
The example on notebook-style should refer to the talk to mention that multiple separators are possible:
https://sphinx-gallery.github.io/stable/tutorials/plot_parse.html#sphx-glr-tutorials-plot-parse-py

Maybe we should have another example for the file with separators that is compatible with atom / vscode. It help users find this feature.

**Comment by lucyleeow** [comment]
Not sure what you mean? The 3 possible separators are mentioned, this is the dev version:

```
You can separate blocks using either a single line of #’s (>=20 columns), `#%%`, or `# %%`. For consistency, it is recommend that you use only one of the above three options in your project.
```

Do you mean we should include both `# %%` and `#%%` in the example `.py` file?

**Comment by GaelVaroquaux** [comment]
I was thinking of adding a different file, and saying something like: this file can be opened with jupytext, atom hydrogen and vscode.

I basically think that it is important to make the "#%%" more visible, and the fact that it plays well with jupytext, atom hydrogen and vscode. Right now, it's not very visible.

Maybe, we should change our default separator, and use "#%%" by default.

Also, maybe a section "suggested editing workflow" somewhere in the docs would help. The workflow of sphinx-gallery is a bit daunting.

**Comment by lucyleeow** [comment]
Actually both `# %%` and `#%%` work for spyder, hydrogen and VScode: https://github.com/sphinx-gallery/sphinx-gallery/pull/518#issuecomment-510944121
Could not test Pycharm (costs money) but [they state](https://blog.jetbrains.com/pycharm/2018/04/pycharm-scientific-mode-with-code-cells/) `#%%`

> I basically think that it is important to make the "#%%" more visible, and the fact that it plays well with jupytext, atom hydrogen and vscode. Right now, it's not very visible.

Do you mean `# %%` more visible? Because atm `#%%` IS the block splitter used in `plot_parse.py`.

Regardless, the documentation could be clarified regarding to workflow and some if it is out of date now (e.g. [Jupyter extension](https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyter) of VScode now deprecated and functionality moved to the Python extension) so will update the doc.

**Comment by GaelVaroquaux** [comment]
> Do you mean # %% more visible?

I don't have a strong opinion on `# %%` vs ``#%%`. You have thought this over better than me, I'll leave it to your call.

> Because atm #%% IS the block splitter used in plot_parse.py.

Hum, technically you are right (my bad). However, if kicks in only after a few `##################`. I would suggest to put the `%%` first, and the `####` only later, as some form of an after thought, mentioning that they don't play well with jupytext et al.

**Comment by lucyleeow** [comment]
> I would suggest to put the `%%` first, and the `####` only later, as some form of an after thought, mentioning that they don't play well with jupytext et al.

Will do.

> I don't have a strong opinion on `# %%` vs ``#%%`.

They both do work - so I might make it clear that although some editors mention one in their doc, both actually work. Admittedly PEP8 would prefer `# %%` but I'm new to this so :woman_shrugging:
