### ISSUE TITLE
How to prevent output to stderr from being captured.

### ISSUE THREAD

**Issue by fumitoh** [sphinx-gallery/sphinx-gallery#618]
Is there a way to prevent output to stderr, not just warnings, from being captured and included in my built documentation?

I have  a following piece of code in my source. How can I stop showing the output in my built docs?

```python
print('Loading PolicyData...', end='', file=sys.stderr)

# Load data...

print('Done.', "({:.2f}secs)".format(this_time - last_time), file=sys.stderr)
```

**Comment by larsoner** [comment]
A principle goal of SG is to make it so that SG's output is a HTML-ified version of what the user would see running the example on their machine. Hence it seems out of scope / against a principle goal to avoid printing the `stdout`/`stderr` the user would see.

One way to go would be to provide some user-extensible mechanism for doing anything:

1. before an example is executed, and
2. after execution completes

We implicitly have (1) in [reset_modules](https://sphinx-gallery.github.io/stable/configuration.html#reset-modules). I think if we added a `reset_modules_end` or `on_example_end` or so that gets executed at the end of running each script (regardless of success or failure), you could in your case patch `sys.stdout` and `sys.stderr` in a custom `reset_modules` callable and un-patch/restore them in a `reset_modules_end` callable. I don't think this would add too much maintenance overhead for us.

**Comment by fumitoh** [comment]
I put the following in `conf.py` and it didn't work. Am I doing it wrong?

```python
def discard_stderr(gallery_conf, fname):
    import os
    import sys
    f = open(os.devnull, 'w')
    sys.stderr = f


sphinx_gallery_conf = {
    # Other configurations here..
    'reset_modules': (discard_stderr,)
}
```

**Comment by larsoner** [comment]
Hmm, maybe it's not a workable solution.

Could you instead use CSS just to hide the code output boxes? Or collapse them? We could look into making them collapsible using CSS/HTML, and then you could add a tiny bit of JavaScript to your pages that makes some or all of them start out collapsed.

**Comment by fumitoh** [comment]
Oh, ok I'll tweak CSS. Thanks for the hint!
