### ISSUE TITLE
Inconsistency with applying & removing sphinx gallery configs

### ISSUE THREAD

**Issue by TomDonoghue** [sphinx-gallery/sphinx-gallery#665]
In trying to add the `remove_config_comments` option (from #487), we noticed an inconsistency in where configs can be put vs. where they get removed from. 

Specifically, configs, (at least `# sphinx_gallery_thumbnail_number = X`) can be put in a text block, and have effect. But the `remove_config_comments` only removes these lines from code blocks. 

So, for example this setup has effect, but the line doesn't get removed from the render:
```
######################################
# Words, words, words.
#
# sphinx_gallery_thumbnail_number = X
#
```

Perhaps these configs weren't really intended to be placed in text blocks? But it does work, and we had them in text blocks. It then took us a while to figure out why the `remove_config_comments` didn't seem to work. 

Options for updating:
- Since config lines currently can be placed in text blocks, and have effect, maybe the  `remove_config_comments` option should drop them from there too?
- If the current behavior can't easily be changed, perhaps a quick note in the documentation about the  `remove_config_comments` option could specify that this only has effect for configs in code blocks.

**Comment by lucyleeow** [comment]
This is due to the first `#` being removed from text blocks by `split_code_and_text_blocks` such that the text block:
```
# %%
# sphinx_gallery_thumbnail_number = 1
```
becomes 'sphinx_gallery_thumbnail_number = 1'. Since the current regex only looks for configs with a `#` at the start (i.e., '# sphinx_gallery_thumbnail_number = 1') configs in text blocks are not removed.

Solutions:
* amend regex to match just the config without `#` at the start. This means that variable assignments in code would be removed if the variable starts with `sphinx_gallery_`. (not sure why/how often people would do this). I could also make the regex more specific so it only matches the 3 configs currently we support so it restricts the variable assignments removed. Of course this makes the code less flexible.
* amend documentation to state that only configs in code blocks are removed
* use one regex for code blocks and another for text blocks, though this adds a fair amount of complexity to the code

What do you think @larsoner ?

**Comment by larsoner** [comment]
I don't think they were ever meant to be in text blocks, so I'd be in favor of making a note in the docs rather than changing any code

**Comment by TomDonoghue** [comment]
Thanks for the quick response / fix!
