### ISSUE TITLE
Calling "plt.show()" raises an ugly warning

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#694]
When a script has "plot.show()" in it, it results in the following ugly warning:
<pre>
UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.
</pre>
Can we capture it and hide it?

**Comment by lucyleeow** [comment]
I've noticed this too but is it new?

You can filter warnings: https://github.com/sphinx-gallery/sphinx-gallery/pull/564

**Comment by GaelVaroquaux** [comment]
> I've noticed this too but is it new?

I don't know. I only noticed it now. I think that old versions of
matplotlib didn't have this.

> You can filter warnings: #564

But shouldn't we filter this one by default? With a way of removing this
filter of course.

**Comment by lucyleeow** [comment]
Well if you want this to be optional we could add a new configuration that can remove various warnings as desired by user. Let's see what others think.

**Comment by larsoner** [comment]
Right now this is what we tell people to do in the docs:
```
warnings.filterwarnings("ignore", category=UserWarning,
                        message='Matplotlib is currently using agg, which is a'
                                ' non-GUI backend, so cannot show the figure.')
```
I guess we can just do this when the builder is initialized. I wouldn't bother with a config var. If people don't want this behavior (I assume YAGNI, though) they can manually remove it from the list of filters -- it can pretty easily be `pop`ed from the `warnings.filters` list in a new `reset_modules` function.

I'd prefer only adding config vars when necessary, because each new one adds additional burden for users to understand and use the library. It starts to become like having a function with a hundred arguments...

**Comment by lucyleeow** [comment]
> I'd prefer only adding config vars when necessary

I totally agree, I just didn't know how to do it optionally otherwise.

> I guess we can just do this when the builder is initialized.

Sounds good. Not sure how to do this. Happy to implement with assistance or if it's easier for you to just do it, happy to watch and learn!

**Comment by larsoner** [comment]
> Happy to implement with assistance or if it's easier for you to just do it, happy to watch and learn!

I'd do it wherever we initialize `matplotlib` to use `agg`, which appears to be in `sphinx_gallery/scrapers.py`

**Comment by GaelVaroquaux** [comment]
> I wouldn't bother with a config var.

Sounds good
