### ISSUE TITLE
Relate warnings and errors on generated rst file back to source Python file / prevent accidental writing of generated files

### ISSUE THREAD

**Issue by ezyang** [sphinx-gallery/sphinx-gallery#725]
When there is a problem in the generated RST file from a Gallery Python file, Sphinx reports the line error in the generated rst file. There's a few problems with this:

1. If you're not paying close attention, you might try editing the RST file to fix the error. But this is the wrong thing to do: you should have edited the source Python file. Some ways to make it harder to make this mistake include (1) removing the write bit from generated files, and (2) inserting a "@generated" comment which is respected by many editors and will warn people when editing
2. It would have been much better to report the error in the source Python file in the first place.

Compilers with the C preprocessor have solved this problem by generating comment lines that let you correspond lines in the generated source back to the original source, and then having the eventual frontend report errors by first translating them back to the original source. sphinx-gallery should do this too. It might be difficult to fix this without also getting Sphinx to play ball (e.g., a logical separation would be for Sphinx to add support for file/line number comments, and then teaching sphinx-gallery to respect them).

Is a feature like this something that would be accepted by sphinx-gallery?

**Comment by larsoner** [comment]
- I'm fine with adding a `@generated` comment to RST if it can be done without showing up in the output (e.g., as `.. @generated` or something)
- I'm fine with creating the RST files as read-only
- The logic for catching the Sphinx warnings, or modifying Sphinx to allow us to do something with the warnings seems like way too much added complexity for the scope of the problem. I'd rather just add to the docs that people need to edit the Python files to fix any errors

**Comment by lucyleeow** [comment]
Some discussion in https://github.com/nilearn/nilearn/pull/2476 about the difficulty in interpreting the Sphinx rst errors, mostly because it isn't so obvious to check the generated rst files.

One suggestion was to include an rst lint step, which may generate more informative error messages. I am not sure how much better they would be - would require checking with some common errors (though @jeromedockes mentioned that they don't pick up on some sphinx rst specific issues).

I think the best debugging 'solution'/suggestion is to check the generated rst files. Maybe we can make this part of the documentation more prominent. WDYT @larsoner ?

cc @GaelVaroquaux

**Comment by larsoner** [comment]
It wouldn't be too much work (I think) for us to:

- create the RST files as read-only
- add a @generated comment, or maybe better, all caps comments at the top:
    ```
    .. DO NOT EDIT.
    .. THIS FILE WAS AUTOMATICALLY GENERATED BY SPHINX-GALLERY.
    .. TO MAKE CHANGES, EDIT THE SOURCE PYTHON FILE:
    .. plot_whatever.py
    .. LINE RANGES ARE GIVEN BELOW.
    ```
- add `.. FROM PYTHON SOURCE LINES: X-Y` to the RST that is generated from the Python source file.

**Comment by GaelVaroquaux** [comment]
Eric, I'm not fully following you. Maybe I'm just dense, and it's clear for others (in which case don't bother). But maybe it's useful to explicit things more.

**Comment by lucyleeow** [comment]
> Eric, I'm not fully following you.

I think Eric is addressing the problem where people try to fix the rST error by changing the generated rST file instead of the source .py file when they see the sphinx rST errors. From the nilearn PR I think the problem is more that people don't realise that there is a generated rST file and this is what they should be looking at to help fix the error.

I feel this may be more of a documentation issue. What do you think of adding a page called 'Practical tips' (or something along those lines)? Here we can go into detail about:

* what the standard output text means
* how to debug code execution and rst errors
* how to execute just one example file for time efficiency
* Any other suggestions?

@larsoner how would you propose this work? Add this for every code/text block in the generated rST?
> add .. FROM PYTHON SOURCE LINES: X-Y to the RST that is generated from the Python source file.

**Comment by GaelVaroquaux** [comment]
> From the nilearn PR I think the problem is more that people don't
> realise that there is a generated rST file and this is what they should
> be looking at to help fix the error.

I think that it was simply that the user didn't see the problems with the
rst code.

In a sense, the error messages are not very explicit. They could for
instance point to the specific place of the line where the problem is,
with something like:

```
Inline markup error on line 190:
    Read the `sphinx-gallery <aa`_ documentation
                               ^ error
```

To improve such error reporting, we would have to contribute to docutils.
Does anyone have an idea of how hard this would be?

**Comment by larsoner** [comment]
Ahh so sounds like two problems:

1. People edit the RST rather than Python file thinking things will be fixed
2. People don't understand the RST errors

My points above are designed to help with mostly (1) and only a little bit of (2). Changing docutils would help with (2).

> Does anyone have an idea of how hard this would be?

I think you still have to go through SourceForge and contribute a patch, this was mine a while back:

https://sourceforge.net/p/docutils/patches/158/

Patches should be submitted here:

https://sourceforge.net/p/docutils/patches/

As for the code, it wasn't always trivial for me at least to figure out what was going on. It would be great if someone could improve the errors, though.
