### ISSUE TITLE
How to scrape for images without executing example scripts

### ISSUE THREAD

**Issue by mschmidt87** [sphinx-gallery/sphinx-gallery#728]
Hi, 
I am trying to create a gallery of my examples *without* executing the scripts but *with* images. The use case is that I have already executed the scripts before building the documentation and the images were saved to disk. Now I want to build the documentation and scrape the folder for images (png files) to add them to the gallery in the documentation.

As far as I understood, this example is supposed to deal with this case: https://sphinx-gallery.github.io/stable/advanced.html#example-2-detecting-image-files-on-disk
(at least that's how I interpret its documentation).

However, when I include this in my `conf.py`, the scraper is only executed for scripts that are run during `make html`, i.e., during building the docs.

For instance, if my files are not covered by the `filename_pattern` in the `sphinx_gallery_conf`, i.e., not executed, the scraper is not run. 
The same happens if I include them in the pattern, but set `plot_gallery: False`.

What am I doing wrong here?
Thanks, and apologies if this has been asked before, I couldn't find any precedent.

**Comment by larsoner** [comment]
> I am trying to create a gallery of my examples without executing the scripts but with images. The use case is that I have already executed the scripts before building the documentation and the images were saved to disk. Now I want to build the documentation and scrape the folder for images (png files) to add them to the gallery in the documentation.

Keep in mind that when running an example, sphinx-gallery generates several other files in addition to images, for example in addition to creating `images/sphx_glr_plot_0_sin_001.png`, `examples/plot_0_sin.py` produces in the `auto_examples/` dir:
```
-rw-rw-r-- 1 larsoner larsoner     853 Jul 21 13:36 plot_0_sin_codeobj.pickle
-rw-rw-r-- 1 larsoner larsoner    4704 Jul 21 13:36 plot_0_sin.ipynb
-rw-rw-r-- 1 larsoner larsoner    3346 Jul 21 13:35 plot_0_sin.py
-rw-rw-r-- 1 larsoner larsoner      32 Jul 21 13:35 plot_0_sin.py.md5
-rw-rw-r-- 1 larsoner larsoner    4858 Jul 21 13:35 plot_0_sin.rst
```
I'm not sure how many of these you officially need to replace, but at the very least you need to make sure that `plot_0_sin.py.md5` contains what running the script would produce, which should be [some variant of what we do](https://github.com/sphinx-gallery/sphinx-gallery/blob/master/sphinx_gallery/gen_rst.py#L723-L724):
```
        with open(script_vars['target_file'] + '.md5', 'w') as file_checksum:
            file_checksum.write(get_md5sum(script_vars['target_file']))
```

Maybe give that a shot and see if it complains about something missing later?

**Comment by mschmidt87** [comment]
Thank you for your reply and the info.

Are you implying that the use case of the example I linked to (the `PNGScraper`) is not what I think it is? My interpretation of the documentation is that this example scraper exactly serves my purpose, i.e., to look for png files on disk and add them to the auto-examples documentation?

**Comment by larsoner** [comment]
> Are you implying that the use case of the example I linked to (the PNGScraper) is not what I think it is? My interpretation of the documentation is that this example scraper exactly serves my purpose, i.e., to look for png files on disk and add them to the auto-examples documentation?

Indeed it's not. The way Sphinx gallery works is to scrape while running a script, and to run scripts when building the docs (this is important for reproducibility among other things). These steps are tightly integrated, and even if we tried to separate them (which would probably be too much code churn for this one use case) it wouldn't really make sense since you wouldn't know which section of the script corresponded to which image (among any other potential problems).

Hence I'm pushing you toward another solution, which is to have things be properly scraped when Sphinx-gallery runs the script for you locally and then make sure you copy over all of the files that Sphinx-gallery creates when running -- or if you don't want Sphinx-gallery to run, create the files yourself manually.

Would it be possible for you to have Sphinx-gallery run the script to generate the files instead of you doing it manually? This would fit much better with the general scope of Sphinx-gallery.

If you really must have pre-run scripts, you could look into using `nbsphinx`, which allows just displaying pre-run cells.

**Comment by mschmidt87** [comment]
Right, okay, thank you for the explanation. Actually, it is possible for me to run the scripts to create the figures. 

I was mostly confused by the documentation because it sounds to me as if it my suggested use case would be possible with it. Particularly this part (from https://sphinx-gallery.github.io/stable/advanced.html#example-2-detecting-image-files-on-disk) seems to imply this:

> Here’s another example that assumes that images have already been written to disk. In this case we won’t generate any image files, we’ll only generate the rST needed to embed them in the documentation.

This issue can be closed then, but I would suggest to consider modifying the wording in the documentation.

Thank you for your help.

**Comment by larsoner** [comment]
Yes that's definitely misleading, because that script still gets *executed*, it's just basically a no-op so it doesn't matter whether or not it gets executed.

Feel free to take a stab at fixing the docs if you're up for it. Maybe "needed to embed them in the documentation. The script will still be executed so that the files get scraped, but they don't need to be produced during the execution." ?

**Comment by mschmidt87** [comment]
Sure, I just created a tiny PR for this. #730
