### ISSUE TITLE
The syle of the CSS needs sanitizing

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#73]
The CSS styles should be as such
<pre>
element {
   prop1: value;
   prop2: value;
}

element2 {
   prop: value;
}
</pre>

**Comment by Titan-C** [comment]
This is an extra complexity/simplicity I have when dealing with CSS. The fact is I stopped dealing with them, I use Firefox developer tools to edit the scss file, which has a nicer syntax and allows nesting. So I'm always sure that the div class I'm editing is only for the scope I wan't and does not contaminate the rest of the styles. I has made my occasional work on CSS a lot simpler.

In the end the css is just an export of the scss. I can export it to an expanded syntax instead of the current nested one.
