### ISSUE TITLE
Pass command line arguments to examples

### ISSUE THREAD

**Issue by mschmidt87** [sphinx-gallery/sphinx-gallery#731]
I have a bunch of examples included in my sphinx-gallery and these examples accept comand-line arguments.
Is it possible to pass command-line arguments through sphinx-gallery? I couldn't find that option in the documentation.

Two use cases would be (in my case):
- control the duration of the execution of examples: It would be nice to control how long the examples take via a command-line arguments (e.g. controlling the number of iterations in some optimization scheme), such that I can build my docs with full functionality in continuous integration, but I'm able to control the runtime so that CI doesn't take too long.
- control the creation of figures. In one example, I am using OpenAI gym, and this causes a problem when I render their environment (rendered with `pyglet`). I receive an error when I execute the example via sphinx-gallery, which is caused by some problem in `pyglet` (as far as I understand). It would be nice to be able to switch off the rendering via the command line.

**Comment by larsoner** [comment]
There is some relevant discussion in #252, and after reading it I can think of two solutions:

1. Allow a `# sphinx_gallery_argv = ..." inline argument to pass the command-line arguments.
2. Allow a `sphinx_gallery_conf['reset_argv']` callable that takes the `script_vars` and `gallery_conf` and does whatever it needs to do to `sys.argv`. By default in sphinx-gallery it would do what's done currentyl, which is equivalent to:

    ```
    import sys
    sys.argv[0] = script_vars['src_file']
    sys.argv[1:] = []
    ```

I prefer (2) since it allows people to control things however they want during doc builds (e.g., via some class), and is also more lightweight from the sphinx-gallery end because we don't need to do any parsing or passing -- just call a callable at the right time (bugs with setting `sys.argv` are at the user's end at that point, not ours).

Any interest in trying to implement this @mschmidt87 ?

**Comment by mschmidt87** [comment]
Sure, I followed your suggestion and opened #732 .
