### ISSUE TITLE
Generalising image_scrapers facility for non-images

### ISSUE THREAD

**Issue by jnothman** [sphinx-gallery/sphinx-gallery#833]
I was wondering if the `image_scrapers` could be repurposed for general artefacts. For example, a script which generated some non-image file output should be able to create download links. Perhaps the scraper would just collect all files in an `artefacts/` directory created by the script, move those files to the correct location, and generate links to appear in the document.

I see the following issues at the moment:
1. Sphinx-Gallery assumes that a fixed set of image filename extensions are appropriate artefacts to be produced by a scraper.
2. Sphinx-Gallery provides specialised handling of images, to downsize them, etc., where for other artefacts, copying verbatim is most appropriate

Solving 2 is easy if we assume that any unknown extension is to be simply copied.

Solving 1 is easy if we simply accept any extension, or get the scraper to nominate valid extensions.

**Comment by jnothman** [comment]
A more friendly solution might be to replace the `image_path_iterator` with a `path_maker` which has the following extra methods:
```
def iterator_for_ext(self, ext : str):
    """use a different extension

    Parameters
    ----------
    ext : str
        Should start with a "."
    """
    def gen():
        for path in self:
            self.paths[-1] = os.path.splitext(self.paths[-1]) + ext
            yield self.paths[-1]

    return gen()

def iterator_for_filenames(self, filenames : List[str]):
    """Use filenames instead of numeric naming

    Parameters
    ----------
    filenames : list of str
    """
    def gen():
        for filename, path in zip(filenames, self):
            self.paths[-1] = self.image_path.format(filename)
            yield self.paths[-1]

    return gen()
```

or something functionally equivalent but not as hacky!

**Comment by lucyleeow** [comment]
Thanks @jnothman, to clarify,

> and generate links to appear in the document

does this mean that images generated would not show as an image in the document but be a link instead?

**Comment by jnothman** [comment]
I'm not thinking images at the moment. I'm thinking other artefacts, for example CSV or XLSX etc.

For these "showing" may not be feasible. The scraper would provide the same functionality: identifying the files generated, moving them into a specified location/name, and generating a way to present them.

**Comment by lucyleeow** [comment]
So presentation would differ depending on, say, file extension?

**Comment by jnothman** [comment]
Presentation is entirely left up to the scraper to decide, isn't it?

**Comment by lucyleeow** [comment]
Ah I understand what you're after now.

I can see the use. It would require a bit of fiddling for the thumbnails, a we assume scraped files are images and use them as thumbnails, but that would be manageable. WDYT @larsoner ?

Would you be interested in implementing @jnothman ?

**Comment by lucyleeow** [comment]
> A more friendly solution might be to replace the image_path_iterator with a path_maker

This sounds reasonable. Would `filenames` param be user configurable ?

**Comment by jnothman** [comment]
Thank you for the more civil issue title :D

> Would filenames param be user configurable ?

The new methods would be used by scrapers to more directly control the list of paths.

> Would you be interested in implementing @jnothman ?

I'm not sure I'll find the availability soon, but I will consider it. While image_scrapers API is experimental, it's unclear how much you'd want to change it. Should we be looking to rename `image_path_iterator` and `ImagePathIterator`?

**Comment by larsoner** [comment]
> Presentation is entirely left up to the scraper to decide, isn't it?

Not quite, because sphinx-gallery still needs to make thumbnails. It uses the generated paths plus their extensions to do this. One way around this problem would be to extend the scraper API to allow returning not just an image, but also a thumbnail for it (and maybe also the RST to use to embed it?).

But to me the primary question is: why even bother using `image_path_iterator` (or any sphinx-gallery path iterator)? You can have an "image scraper" (in name only) that does something smart and returns some suitable RST (can be raw HTML) that will be embedded by sphinx-gallery, but never increments the SG iterator. (You can create have an iterator for paths of your own if you want.) This is exactly what we do in MNE-Python with the Report scraper -- we embed HTML documents inline in our files:

https://mne.tools/dev/auto_tutorials/intro/70_report.html#basic-reports

Using this code:

https://github.com/mne-tools/mne-python/blob/c0d431acf0307a8bf92ab01995397194563f6920/doc/conf.py#L335-L336
https://github.com/mne-tools/mne-python/blob/c0d431acf0307a8bf92ab01995397194563f6920/doc/conf.py#L1065-L1068
https://github.com/mne-tools/mne-python/blob/main/mne/report.py#L2239-L2300

**Comment by lucyleeow** [comment]
> we embed HTML documents inline in our files

This could also be done readily by adding a `_repr_html_` and using the `capture_repr`.

**Comment by jnothman** [comment]
You might be right, @larsoner, that all you need is to return appropriate rendering. I think I just got lost in an idea. I'll think about whether advantages remain...

**Comment by jnothman** [comment]
Thanks for the sanity check!!

**Comment by jnothman** [comment]
repr is not appropriate in some cases, where we want this not to be mediated public APIs of objects in the script.

I think I had imagined sphinx-gallery's execution to be sandboxed in a temporary directory, such that artifacts would need to be exported from that directory to be used, but it seems that's not the case. Closing until I think of valid use cases!
