### ISSUE TITLE
Galleries using bokeh

### ISSUE THREAD

**Issue by nss350** [sphinx-gallery/sphinx-gallery#841]
Hi,
I've searched in the issues and more widely to understand whether there is support for bokeh plots in sphinx gallery. I found some issues from 2019 that suggested that bokeh plots maybe supported, but wanted to double check before setting down on a particular development pathway with an incorrect assumption.

Thanks for any help.

**Comment by larsoner** [comment]
From a very brief search it looks like they rolled their own gallery generator:

https://docs.bokeh.org/en/latest/docs/reference/sphinxext.html#module-bokeh.sphinxext.bokeh_gallery

Nowadays we provide a flexible `scrapers` option so you might be able to create your own sphinx-gallery scraper for Bokeh. But really it seems lower effort to figure out how to use their directive. You'll have to ask them / open an issue to be sure, though.

Closing since I don't think any changes are needed from SG, but perhaps it might be nice to add a note to our website that links to their gallery stuff at some point to save the next person some time!

**Comment by nss350** [comment]
Hi @larsoner, thanks for your reply. I did check with bokeh and saw the bokeh gallery, but seeing the lack of docs, I decided to check in here first before proceeding. The plan is to use this functionality in a readthedocs compatible way and I have some larger data that it runs on that does not sit in my project repository, therefore there is a bit of complexity.

**Comment by bryevdv** [comment]
Obviously a bit late to the party, but for the benefit of anyone that might wander here in the future: The `bokeh-plot` directive for embedding individual Bokeh objects into sphinx pages has always been well-documented, and is suitable for general use:

https://docs.bokeh.org/en/latest/docs/reference/sphinxext.html#module-bokeh.sphinxext.bokeh_plot

But the `bokeh-gallery` directive is specialized and really only useful for Bokeh's own docs, which is why it is more or less undocumented. Perhaps we should have hidden it away entirely. 

Given the how customizable SG has become over the last several years, I am sure an SG scraper for Bokeh is feasible. It's not something I currently have bandwidth for, but I am happy to lend Bokeh expertise to anyone who would like to make a stab at one.
