### ISSUE TITLE
Why is sphinx_gallery imported in setup.py

### ISSUE THREAD

**Issue by amueller** [sphinx-gallery/sphinx-gallery#89]
It doesn't seem to be used in the config, right?

**Comment by Titan-C** [comment]
It is needed, so that you can declare in the extension to be used. Declaring the search path for extensions I think is also equivalent.
An older reason for that is that previously I was used to load the _static path of sphinx-gallery for sphinx to reach the default thumbnail and the CSS file. Now that gets exposed while the gallery is being build.

**Comment by amueller** [comment]
I just ran it without it and it seems to work... you declare the extension just as the string, right?

**Comment by Titan-C** [comment]
> I just ran it without it and it seems to work... you declare the extension just as the string, right?

Then it is the remaining of an old use case. The declaration of the extension is the string inside the list extension in the conf.py file

Now that I read with more attention the issue question. In setup.py it is used to give the version number. And I do think we need it there.

**Comment by amueller** [comment]
sorry I was unclear. I wasn't talking about the sphinx_gallery setup.py, but the fact that the docs state you should import sphinx_gallery in your setup.py:
http://sphinx-gallery.readthedocs.org/en/latest/getting_started.html
